//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace MedinetCRMService.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSCallCenterSoap", Namespace="http://Localhost/")]
    public partial class WSCallCenter : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LineasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImeisOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImeisActivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmpresasOperationCompleted;
        
        private System.Threading.SendOrPostCallback TablasDescargarOperationCompleted;
        
        private System.Threading.SendOrPostCallback TablasIncluirOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarImeiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParametrosOperationCompleted;
        
        private System.Threading.SendOrPostCallback VersionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarEquipoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImeisFacturadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarSMSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSCallCenter() {
            this.Url = global::MedinetCRMService.Properties.Settings.Default.MedinetCRMService_localhost_WSCallCenter;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LineasCompletedEventHandler LineasCompleted;
        
        /// <remarks/>
        public event ImeisCompletedEventHandler ImeisCompleted;
        
        /// <remarks/>
        public event ImeisActivosCompletedEventHandler ImeisActivosCompleted;
        
        /// <remarks/>
        public event EmpresasCompletedEventHandler EmpresasCompleted;
        
        /// <remarks/>
        public event TablasDescargarCompletedEventHandler TablasDescargarCompleted;
        
        /// <remarks/>
        public event TablasIncluirCompletedEventHandler TablasIncluirCompleted;
        
        /// <remarks/>
        public event BuscarImeiCompletedEventHandler BuscarImeiCompleted;
        
        /// <remarks/>
        public event ParametrosCompletedEventHandler ParametrosCompleted;
        
        /// <remarks/>
        public event VersionesCompletedEventHandler VersionesCompleted;
        
        /// <remarks/>
        public event registrarEquipoCompletedEventHandler registrarEquipoCompleted;
        
        /// <remarks/>
        public event ImeisFacturadorCompletedEventHandler ImeisFacturadorCompleted;
        
        /// <remarks/>
        public event enviarSMSCompletedEventHandler enviarSMSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Localhost/Lineas", RequestNamespace="http://Localhost/", ResponseNamespace="http://Localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Linea[] Lineas() {
            object[] results = this.Invoke("Lineas", new object[0]);
            return ((Linea[])(results[0]));
        }
        
        /// <remarks/>
        public void LineasAsync() {
            this.LineasAsync(null);
        }
        
        /// <remarks/>
        public void LineasAsync(object userState) {
            if ((this.LineasOperationCompleted == null)) {
                this.LineasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLineasOperationCompleted);
            }
            this.InvokeAsync("Lineas", new object[0], this.LineasOperationCompleted, userState);
        }
        
        private void OnLineasOperationCompleted(object arg) {
            if ((this.LineasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LineasCompleted(this, new LineasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Localhost/Imeis", RequestNamespace="http://Localhost/", ResponseNamespace="http://Localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Imei[] Imeis() {
            object[] results = this.Invoke("Imeis", new object[0]);
            return ((Imei[])(results[0]));
        }
        
        /// <remarks/>
        public void ImeisAsync() {
            this.ImeisAsync(null);
        }
        
        /// <remarks/>
        public void ImeisAsync(object userState) {
            if ((this.ImeisOperationCompleted == null)) {
                this.ImeisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImeisOperationCompleted);
            }
            this.InvokeAsync("Imeis", new object[0], this.ImeisOperationCompleted, userState);
        }
        
        private void OnImeisOperationCompleted(object arg) {
            if ((this.ImeisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImeisCompleted(this, new ImeisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Localhost/ImeisActivos", RequestNamespace="http://Localhost/", ResponseNamespace="http://Localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Imei[] ImeisActivos() {
            object[] results = this.Invoke("ImeisActivos", new object[0]);
            return ((Imei[])(results[0]));
        }
        
        /// <remarks/>
        public void ImeisActivosAsync() {
            this.ImeisActivosAsync(null);
        }
        
        /// <remarks/>
        public void ImeisActivosAsync(object userState) {
            if ((this.ImeisActivosOperationCompleted == null)) {
                this.ImeisActivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImeisActivosOperationCompleted);
            }
            this.InvokeAsync("ImeisActivos", new object[0], this.ImeisActivosOperationCompleted, userState);
        }
        
        private void OnImeisActivosOperationCompleted(object arg) {
            if ((this.ImeisActivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImeisActivosCompleted(this, new ImeisActivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Localhost/Empresas", RequestNamespace="http://Localhost/", ResponseNamespace="http://Localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empresa[] Empresas() {
            object[] results = this.Invoke("Empresas", new object[0]);
            return ((Empresa[])(results[0]));
        }
        
        /// <remarks/>
        public void EmpresasAsync() {
            this.EmpresasAsync(null);
        }
        
        /// <remarks/>
        public void EmpresasAsync(object userState) {
            if ((this.EmpresasOperationCompleted == null)) {
                this.EmpresasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmpresasOperationCompleted);
            }
            this.InvokeAsync("Empresas", new object[0], this.EmpresasOperationCompleted, userState);
        }
        
        private void OnEmpresasOperationCompleted(object arg) {
            if ((this.EmpresasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmpresasCompleted(this, new EmpresasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Localhost/TablasDescargar", RequestNamespace="http://Localhost/", ResponseNamespace="http://Localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tabla[] TablasDescargar() {
            object[] results = this.Invoke("TablasDescargar", new object[0]);
            return ((Tabla[])(results[0]));
        }
        
        /// <remarks/>
        public void TablasDescargarAsync() {
            this.TablasDescargarAsync(null);
        }
        
        /// <remarks/>
        public void TablasDescargarAsync(object userState) {
            if ((this.TablasDescargarOperationCompleted == null)) {
                this.TablasDescargarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTablasDescargarOperationCompleted);
            }
            this.InvokeAsync("TablasDescargar", new object[0], this.TablasDescargarOperationCompleted, userState);
        }
        
        private void OnTablasDescargarOperationCompleted(object arg) {
            if ((this.TablasDescargarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TablasDescargarCompleted(this, new TablasDescargarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Localhost/TablasIncluir", RequestNamespace="http://Localhost/", ResponseNamespace="http://Localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tabla[] TablasIncluir() {
            object[] results = this.Invoke("TablasIncluir", new object[0]);
            return ((Tabla[])(results[0]));
        }
        
        /// <remarks/>
        public void TablasIncluirAsync() {
            this.TablasIncluirAsync(null);
        }
        
        /// <remarks/>
        public void TablasIncluirAsync(object userState) {
            if ((this.TablasIncluirOperationCompleted == null)) {
                this.TablasIncluirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTablasIncluirOperationCompleted);
            }
            this.InvokeAsync("TablasIncluir", new object[0], this.TablasIncluirOperationCompleted, userState);
        }
        
        private void OnTablasIncluirOperationCompleted(object arg) {
            if ((this.TablasIncluirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TablasIncluirCompleted(this, new TablasIncluirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Localhost/BuscarImei", RequestNamespace="http://Localhost/", ResponseNamespace="http://Localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Imei[] BuscarImei(string imei) {
            object[] results = this.Invoke("BuscarImei", new object[] {
                        imei});
            return ((Imei[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarImeiAsync(string imei) {
            this.BuscarImeiAsync(imei, null);
        }
        
        /// <remarks/>
        public void BuscarImeiAsync(string imei, object userState) {
            if ((this.BuscarImeiOperationCompleted == null)) {
                this.BuscarImeiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarImeiOperationCompleted);
            }
            this.InvokeAsync("BuscarImei", new object[] {
                        imei}, this.BuscarImeiOperationCompleted, userState);
        }
        
        private void OnBuscarImeiOperationCompleted(object arg) {
            if ((this.BuscarImeiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarImeiCompleted(this, new BuscarImeiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Localhost/Parametros", RequestNamespace="http://Localhost/", ResponseNamespace="http://Localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpresaParametro[] Parametros(int empre) {
            object[] results = this.Invoke("Parametros", new object[] {
                        empre});
            return ((EmpresaParametro[])(results[0]));
        }
        
        /// <remarks/>
        public void ParametrosAsync(int empre) {
            this.ParametrosAsync(empre, null);
        }
        
        /// <remarks/>
        public void ParametrosAsync(int empre, object userState) {
            if ((this.ParametrosOperationCompleted == null)) {
                this.ParametrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParametrosOperationCompleted);
            }
            this.InvokeAsync("Parametros", new object[] {
                        empre}, this.ParametrosOperationCompleted, userState);
        }
        
        private void OnParametrosOperationCompleted(object arg) {
            if ((this.ParametrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParametrosCompleted(this, new ParametrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Localhost/Versiones", RequestNamespace="http://Localhost/", ResponseNamespace="http://Localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ControlVersion[] Versiones() {
            object[] results = this.Invoke("Versiones", new object[0]);
            return ((ControlVersion[])(results[0]));
        }
        
        /// <remarks/>
        public void VersionesAsync() {
            this.VersionesAsync(null);
        }
        
        /// <remarks/>
        public void VersionesAsync(object userState) {
            if ((this.VersionesOperationCompleted == null)) {
                this.VersionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionesOperationCompleted);
            }
            this.InvokeAsync("Versiones", new object[0], this.VersionesOperationCompleted, userState);
        }
        
        private void OnVersionesOperationCompleted(object arg) {
            if ((this.VersionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionesCompleted(this, new VersionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Localhost/registrarEquipo", RequestNamespace="http://Localhost/", ResponseNamespace="http://Localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool registrarEquipo(string imei) {
            object[] results = this.Invoke("registrarEquipo", new object[] {
                        imei});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void registrarEquipoAsync(string imei) {
            this.registrarEquipoAsync(imei, null);
        }
        
        /// <remarks/>
        public void registrarEquipoAsync(string imei, object userState) {
            if ((this.registrarEquipoOperationCompleted == null)) {
                this.registrarEquipoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarEquipoOperationCompleted);
            }
            this.InvokeAsync("registrarEquipo", new object[] {
                        imei}, this.registrarEquipoOperationCompleted, userState);
        }
        
        private void OnregistrarEquipoOperationCompleted(object arg) {
            if ((this.registrarEquipoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarEquipoCompleted(this, new registrarEquipoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Localhost/ImeisFacturador", RequestNamespace="http://Localhost/", ResponseNamespace="http://Localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ImeisFacturador(string fDesde, string fHasta, int idEmpresa) {
            object[] results = this.Invoke("ImeisFacturador", new object[] {
                        fDesde,
                        fHasta,
                        idEmpresa});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ImeisFacturadorAsync(string fDesde, string fHasta, int idEmpresa) {
            this.ImeisFacturadorAsync(fDesde, fHasta, idEmpresa, null);
        }
        
        /// <remarks/>
        public void ImeisFacturadorAsync(string fDesde, string fHasta, int idEmpresa, object userState) {
            if ((this.ImeisFacturadorOperationCompleted == null)) {
                this.ImeisFacturadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImeisFacturadorOperationCompleted);
            }
            this.InvokeAsync("ImeisFacturador", new object[] {
                        fDesde,
                        fHasta,
                        idEmpresa}, this.ImeisFacturadorOperationCompleted, userState);
        }
        
        private void OnImeisFacturadorOperationCompleted(object arg) {
            if ((this.ImeisFacturadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImeisFacturadorCompleted(this, new ImeisFacturadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Localhost/enviarSMS", RequestNamespace="http://Localhost/", ResponseNamespace="http://Localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool enviarSMS(string rifEmpresa, long idMensaje, string telefono, string texto) {
            object[] results = this.Invoke("enviarSMS", new object[] {
                        rifEmpresa,
                        idMensaje,
                        telefono,
                        texto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void enviarSMSAsync(string rifEmpresa, long idMensaje, string telefono, string texto) {
            this.enviarSMSAsync(rifEmpresa, idMensaje, telefono, texto, null);
        }
        
        /// <remarks/>
        public void enviarSMSAsync(string rifEmpresa, long idMensaje, string telefono, string texto, object userState) {
            if ((this.enviarSMSOperationCompleted == null)) {
                this.enviarSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarSMSOperationCompleted);
            }
            this.InvokeAsync("enviarSMS", new object[] {
                        rifEmpresa,
                        idMensaje,
                        telefono,
                        texto}, this.enviarSMSOperationCompleted, userState);
        }
        
        private void OnenviarSMSOperationCompleted(object arg) {
            if ((this.enviarSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarSMSCompleted(this, new enviarSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Localhost/")]
    public partial class Linea {
        
        private string nombreLineaField;
        
        private string codigoLineaField;
        
        /// <remarks/>
        public string NombreLinea {
            get {
                return this.nombreLineaField;
            }
            set {
                this.nombreLineaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoLinea {
            get {
                return this.codigoLineaField;
            }
            set {
                this.codigoLineaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Localhost/")]
    public partial class ControlVersion {
        
        private int idField;
        
        private string versionField;
        
        private System.DateTime fechaPublicacionField;
        
        private bool statusField;
        
        private string archivoField;
        
        private int codigoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaPublicacion {
            get {
                return this.fechaPublicacionField;
            }
            set {
                this.fechaPublicacionField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Localhost/")]
    public partial class EmpresaParametro {
        
        private string nombreField;
        
        private string valorField;
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Localhost/")]
    public partial class Tabla {
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Localhost/")]
    public partial class Empresa {
        
        private int idField;
        
        private string nombreField;
        
        private string fotoField;
        
        private string rifField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
            }
        }
        
        /// <remarks/>
        public string Rif {
            get {
                return this.rifField;
            }
            set {
                this.rifField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Localhost/")]
    public partial class Imei {
        
        private int idField;
        
        private string numeroIMEIField;
        
        private int empresa_IdField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        private bool statusField;
        
        private string rifField;
        
        private string nombreEmpresaField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroIMEI {
            get {
                return this.numeroIMEIField;
            }
            set {
                this.numeroIMEIField = value;
            }
        }
        
        /// <remarks/>
        public int Empresa_Id {
            get {
                return this.empresa_IdField;
            }
            set {
                this.empresa_IdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string rif {
            get {
                return this.rifField;
            }
            set {
                this.rifField = value;
            }
        }
        
        /// <remarks/>
        public string nombreEmpresa {
            get {
                return this.nombreEmpresaField;
            }
            set {
                this.nombreEmpresaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void LineasCompletedEventHandler(object sender, LineasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LineasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LineasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Linea[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Linea[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ImeisCompletedEventHandler(object sender, ImeisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImeisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImeisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Imei[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Imei[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ImeisActivosCompletedEventHandler(object sender, ImeisActivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImeisActivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImeisActivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Imei[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Imei[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void EmpresasCompletedEventHandler(object sender, EmpresasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmpresasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmpresasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empresa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empresa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TablasDescargarCompletedEventHandler(object sender, TablasDescargarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TablasDescargarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TablasDescargarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tabla[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tabla[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TablasIncluirCompletedEventHandler(object sender, TablasIncluirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TablasIncluirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TablasIncluirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tabla[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tabla[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void BuscarImeiCompletedEventHandler(object sender, BuscarImeiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarImeiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarImeiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Imei[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Imei[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ParametrosCompletedEventHandler(object sender, ParametrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParametrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParametrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmpresaParametro[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmpresaParametro[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void VersionesCompletedEventHandler(object sender, VersionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ControlVersion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ControlVersion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void registrarEquipoCompletedEventHandler(object sender, registrarEquipoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarEquipoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarEquipoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ImeisFacturadorCompletedEventHandler(object sender, ImeisFacturadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImeisFacturadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImeisFacturadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void enviarSMSCompletedEventHandler(object sender, enviarSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591