//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Data;
    //using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MedinetWebEntities : DbContext
    {
        public MedinetWebEntities()
            : base("name=MedinetWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MW_LocacionPaises> MW_LocacionPaises { get; set; }
        public DbSet<MW_CadenaFarmacias> MW_CadenaFarmacias { get; set; }
        public DbSet<MW_CaracteristicaVisitas> MW_CaracteristicaVisitas { get; set; }
        public DbSet<MW_ConsideracionMedicos> MW_ConsideracionMedicos { get; set; }
        public DbSet<MW_DeporteMedicos> MW_DeporteMedicos { get; set; }
        public DbSet<MW_Especialidades> MW_Especialidades { get; set; }
        public DbSet<MW_Galenicas> MW_Galenicas { get; set; }
        public DbSet<MW_IdiomaMedicos> MW_IdiomaMedicos { get; set; }
        public DbSet<MW_Laboratorios> MW_Laboratorios { get; set; }
        public DbSet<MW_OcupacionMedicos> MW_OcupacionMedicos { get; set; }
        public DbSet<MW_Patologias> MW_Patologias { get; set; }
        public DbSet<MW_Posiciones> MW_Posiciones { get; set; }
        public DbSet<MW_Regiones> MW_Regiones { get; set; }
        public DbSet<MW_ServicioHospitales> MW_ServicioHospitales { get; set; }
        public DbSet<MW_SolicitudVisitas> MW_SolicitudVisitas { get; set; }
        public DbSet<MW_TipoMedicos> MW_TipoMedicos { get; set; }
        public DbSet<MW_TipoVisitaFarmacias> MW_TipoVisitaFarmacias { get; set; }
        public DbSet<MW_TipoVisitaHospitales> MW_TipoVisitaHospitales { get; set; }
        public DbSet<MW_MotivoVisitas> MW_MotivoVisitas { get; set; }
        public DbSet<MW_ClasificacionFarmacias> MW_ClasificacionFarmacias { get; set; }
        public DbSet<MW_Droguerias> MW_Droguerias { get; set; }
        public DbSet<MW_ConvenioFarmacias> MW_ConvenioFarmacias { get; set; }
        public DbSet<MW_ActivEspeciales> MW_ActivEspeciales { get; set; }
        public DbSet<MW_Lineas> MW_Lineas { get; set; }
        public DbSet<MW_Marcas> MW_Marcas { get; set; }
        public DbSet<MW_LineasEspecialidades> MW_LineasEspecialidades { get; set; }
        public DbSet<MW_Instituciones> MW_Instituciones { get; set; }
        public DbSet<MW_MarcasCompetencias> MW_MarcasCompetencias { get; set; }
        public DbSet<MW_MarcasLineas> MW_MarcasLineas { get; set; }
        public DbSet<MW_BeneficioVisitas> MW_BeneficioVisitas { get; set; }
        public DbSet<MW_ClasificacionMedicos> MW_ClasificacionMedicos { get; set; }
        public DbSet<MW_EsquemasPromocionales> MW_EsquemasPromocionales { get; set; }
        public DbSet<MW_Zonas> MW_Zonas { get; set; }
        public DbSet<MW_ConceptoDescuentos> MW_ConceptoDescuentos { get; set; }
        public DbSet<MW_RegionesEstados> MW_RegionesEstados { get; set; }
        public DbSet<MW_Aprobaciones> MW_Aprobaciones { get; set; }
        public DbSet<MW_Ciclos> MW_Ciclos { get; set; }
        public DbSet<MW_Cargos> MW_Cargos { get; set; }
        public DbSet<MW_Roles> MW_Roles { get; set; }
        public DbSet<MWS_CargaInv> MWS_CargaInv { get; set; }
        public DbSet<MWS_TipoArticulos> MWS_TipoArticulos { get; set; }
        public DbSet<MWS_UnidadManejo> MWS_UnidadManejo { get; set; }
        public DbSet<MWS_ConfigDistribucion> MWS_ConfigDistribucion { get; set; }
        public DbSet<MWS_FicheroEspejo> MWS_FicheroEspejo { get; set; }
        public DbSet<MW_Publicaciones> MW_Publicaciones { get; set; }
        public DbSet<MW_Umbrales> MW_Umbrales { get; set; }
        public DbSet<MWS_NoContFichero> MWS_NoContFichero { get; set; }
        public DbSet<MW_Farmacias> MW_Farmacias { get; set; }
        public DbSet<MW_Hospitales> MW_Hospitales { get; set; }
        public DbSet<MW_LocacionBricks> MW_LocacionBricks { get; set; }
        public DbSet<MW_LocacionEstados> MW_LocacionEstados { get; set; }
        public DbSet<MWS_NotaEntregaDetalle> MWS_NotaEntregaDetalle { get; set; }
        public DbSet<MWS_NotaEntregaCabecera> MWS_NotaEntregaCabecera { get; set; }
        public DbSet<MW_Medicos> MW_Medicos { get; set; }
        public DbSet<MWS_Configuraciones> MWS_Configuraciones { get; set; }
        public DbSet<MW_Usuarios> MW_Usuarios { get; set; }
        public DbSet<MW_VisitadoresHistorial> MW_VisitadoresHistorial { get; set; }
        public DbSet<MW_AprobacionesUsuarios> MW_AprobacionesUsuarios { get; set; }
        public DbSet<MW_DescuentosUsuarios> MW_DescuentosUsuarios { get; set; }
        public DbSet<MW_FichasAcceso> MW_FichasAcceso { get; set; }
        public DbSet<MW_UsuariosResponsabilidades> MW_UsuariosResponsabilidades { get; set; }
        public DbSet<MWS_UsuarioAprobacion> MWS_UsuarioAprobacion { get; set; }
        public DbSet<MWS_UsuarioDispensado> MWS_UsuarioDispensado { get; set; }
        public DbSet<MWS_ValidaVisitadores> MWS_ValidaVisitadores { get; set; }
        public DbSet<MWS_CierreDistribucion> MWS_CierreDistribucion { get; set; }
        public DbSet<MWS_AprDistribucion> MWS_AprDistribucion { get; set; }
        public DbSet<MWS_Articulos> MWS_Articulos { get; set; }
        public DbSet<MWS_Existencias> MWS_Existencias { get; set; }
        public DbSet<MW_UsuariosRoles> MW_UsuariosRoles { get; set; }
        public DbSet<MW_DrogueriasAlmacenes> MW_DrogueriasAlmacenes { get; set; }
        public DbSet<MW_LaboratoriosDroguerias> MW_LaboratoriosDroguerias { get; set; }
        public DbSet<MW_DrogueriasProductos> MW_DrogueriasProductos { get; set; }
        public DbSet<MW_Productos> MW_Productos { get; set; }
        public DbSet<MWS_MarcasSIDEX> MWS_MarcasSIDEX { get; set; }
        public DbSet<MWS_ArticulosRechazados> MWS_ArticulosRechazados { get; set; }
        public DbSet<MWS_ExistenciasRechazadas> MWS_ExistenciasRechazadas { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SP_MW_AprobacionIsAllow(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_MW_AprobacionIsAllow", usuarioParameter);
        }
    
        public virtual ObjectResult<SP_MW_Ciclos_Act_Result> SP_MW_Ciclos_Act()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Ciclos_Act_Result>("SP_MW_Ciclos_Act");
        }
    
        public virtual ObjectResult<SP_MW_Ciclos_DesUsu_Result> SP_MW_Ciclos_DesUsu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Ciclos_DesUsu_Result>("SP_MW_Ciclos_DesUsu");
        }
    
        public virtual ObjectResult<SP_MW_CiclosVisitadores_Result> SP_MW_CiclosVisitadores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CiclosVisitadores_Result>("SP_MW_CiclosVisitadores");
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorClasif_Result> SP_MW_CoberturaPorClasif(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorClasif_Result>("SP_MW_CoberturaPorClasif", cicloParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorClasifReg_Result> SP_MW_CoberturaPorClasifReg(Nullable<int> ciclo, Nullable<int> clasificacion)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var clasificacionParameter = clasificacion.HasValue ?
                new ObjectParameter("clasificacion", clasificacion) :
                new ObjectParameter("clasificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorClasifReg_Result>("SP_MW_CoberturaPorClasifReg", cicloParameter, clasificacionParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorClasifRegLin_Result> SP_MW_CoberturaPorClasifRegLin(Nullable<int> ciclo, Nullable<int> clasificacion, Nullable<int> region)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var clasificacionParameter = clasificacion.HasValue ?
                new ObjectParameter("clasificacion", clasificacion) :
                new ObjectParameter("clasificacion", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorClasifRegLin_Result>("SP_MW_CoberturaPorClasifRegLin", cicloParameter, clasificacionParameter, regionParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorClasifRegLinVis_Result> SP_MW_CoberturaPorClasifRegLinVis(Nullable<int> ciclo, Nullable<int> clasificacion, Nullable<int> region, Nullable<int> linea)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var clasificacionParameter = clasificacion.HasValue ?
                new ObjectParameter("clasificacion", clasificacion) :
                new ObjectParameter("clasificacion", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorClasifRegLinVis_Result>("SP_MW_CoberturaPorClasifRegLinVis", cicloParameter, clasificacionParameter, regionParameter, lineaParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorClasifRegLinVisEsp_Result> SP_MW_CoberturaPorClasifRegLinVisEsp(Nullable<int> ciclo, Nullable<int> clasificacion, Nullable<int> region, Nullable<int> linea, Nullable<int> visitador)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var clasificacionParameter = clasificacion.HasValue ?
                new ObjectParameter("clasificacion", clasificacion) :
                new ObjectParameter("clasificacion", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorClasifRegLinVisEsp_Result>("SP_MW_CoberturaPorClasifRegLinVisEsp", cicloParameter, clasificacionParameter, regionParameter, lineaParameter, visitadorParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorClasifRegLinVisEspMed_Result> SP_MW_CoberturaPorClasifRegLinVisEspMed(Nullable<int> ciclo, Nullable<int> clasificacion, Nullable<int> region, Nullable<int> linea, Nullable<int> visitador, Nullable<int> especialidad)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var clasificacionParameter = clasificacion.HasValue ?
                new ObjectParameter("clasificacion", clasificacion) :
                new ObjectParameter("clasificacion", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            var especialidadParameter = especialidad.HasValue ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorClasifRegLinVisEspMed_Result>("SP_MW_CoberturaPorClasifRegLinVisEspMed", cicloParameter, clasificacionParameter, regionParameter, lineaParameter, visitadorParameter, especialidadParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorEsp_Result> SP_MW_CoberturaPorEsp(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorEsp_Result>("SP_MW_CoberturaPorEsp", cicloParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorEspReg_Result> SP_MW_CoberturaPorEspReg(Nullable<int> ciclo, Nullable<int> especialidad)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var especialidadParameter = especialidad.HasValue ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorEspReg_Result>("SP_MW_CoberturaPorEspReg", cicloParameter, especialidadParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorEspRegLin_Result> SP_MW_CoberturaPorEspRegLin(Nullable<int> ciclo, Nullable<int> especialidad, Nullable<int> region)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var especialidadParameter = especialidad.HasValue ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorEspRegLin_Result>("SP_MW_CoberturaPorEspRegLin", cicloParameter, especialidadParameter, regionParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorEspRegLinVis_Result> SP_MW_CoberturaPorEspRegLinVis(Nullable<int> ciclo, Nullable<int> especialidad, Nullable<int> region, Nullable<int> linea)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var especialidadParameter = especialidad.HasValue ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorEspRegLinVis_Result>("SP_MW_CoberturaPorEspRegLinVis", cicloParameter, especialidadParameter, regionParameter, lineaParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorEspRegLinVisMed_Result> SP_MW_CoberturaPorEspRegLinVisMed(Nullable<int> ciclo, Nullable<int> especialidad, Nullable<int> region, Nullable<int> linea, Nullable<int> visitador)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var especialidadParameter = especialidad.HasValue ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorEspRegLinVisMed_Result>("SP_MW_CoberturaPorEspRegLinVisMed", cicloParameter, especialidadParameter, regionParameter, lineaParameter, visitadorParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorReg_Result> SP_MW_CoberturaPorReg(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorReg_Result>("SP_MW_CoberturaPorReg", cicloParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorRegLin_Result> SP_MW_CoberturaPorRegLin(Nullable<int> ciclo, Nullable<int> region)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorRegLin_Result>("SP_MW_CoberturaPorRegLin", cicloParameter, regionParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorRegLinVis_Result> SP_MW_CoberturaPorRegLinVis(Nullable<int> ciclo, Nullable<int> region, Nullable<int> linea)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorRegLinVis_Result>("SP_MW_CoberturaPorRegLinVis", cicloParameter, regionParameter, lineaParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorRegLinVisEsp_Result> SP_MW_CoberturaPorRegLinVisEsp(Nullable<int> ciclo, Nullable<int> region, Nullable<int> linea, Nullable<int> visitador)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorRegLinVisEsp_Result>("SP_MW_CoberturaPorRegLinVisEsp", cicloParameter, regionParameter, lineaParameter, visitadorParameter);
        }
    
        public virtual ObjectResult<SP_MW_CoberturaPorRegLinVisEspMed_Result> SP_MW_CoberturaPorRegLinVisEspMed(Nullable<int> ciclo, Nullable<int> region, Nullable<int> linea, Nullable<int> visitador, Nullable<int> especialidad)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            var especialidadParameter = especialidad.HasValue ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_CoberturaPorRegLinVisEspMed_Result>("SP_MW_CoberturaPorRegLinVisEspMed", cicloParameter, regionParameter, lineaParameter, visitadorParameter, especialidadParameter);
        }
    
        public virtual ObjectResult<SP_MW_Dashboard_AltasBajas_Result> SP_MW_Dashboard_AltasBajas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Dashboard_AltasBajas_Result>("SP_MW_Dashboard_AltasBajas");
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_MW_Dashboard_PromedioFichas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_MW_Dashboard_PromedioFichas");
        }
    
        public virtual ObjectResult<SP_MW_Dashboard_TopVisitadores_Result> SP_MW_Dashboard_TopVisitadores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Dashboard_TopVisitadores_Result>("SP_MW_Dashboard_TopVisitadores");
        }
    
        public virtual ObjectResult<SP_MW_DescuentosUsuarios_ConDesUsu_Result> SP_MW_DescuentosUsuarios_ConDesUsu(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_DescuentosUsuarios_ConDesUsu_Result>("SP_MW_DescuentosUsuarios_ConDesUsu", cicloParameter);
        }
    
        public virtual ObjectResult<SP_MW_DescuentosUsuarios_DesUsu_Result> SP_MW_DescuentosUsuarios_DesUsu(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_DescuentosUsuarios_DesUsu_Result>("SP_MW_DescuentosUsuarios_DesUsu", usuarioParameter);
        }
    
        public virtual ObjectResult<SP_MW_DescuentosVisitadores_DesVis_Result> SP_MW_DescuentosVisitadores_DesVis(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_DescuentosVisitadores_DesVis_Result>("SP_MW_DescuentosVisitadores_DesVis", cicloParameter);
        }
    
        public virtual ObjectResult<SP_MW_Especialidades_EsqPro_Result> SP_MW_Especialidades_EsqPro(Nullable<int> linea)
        {
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Especialidades_EsqPro_Result>("SP_MW_Especialidades_EsqPro", lineaParameter);
        }
    
        public virtual ObjectResult<SP_MW_FichaAcceso_Result> SP_MW_FichaAcceso(Nullable<int> fichaAcceso)
        {
            var fichaAccesoParameter = fichaAcceso.HasValue ?
                new ObjectParameter("fichaAcceso", fichaAcceso) :
                new ObjectParameter("fichaAcceso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_FichaAcceso_Result>("SP_MW_FichaAcceso", fichaAccesoParameter);
        }
    
        public virtual ObjectResult<SP_MW_FicheroVisitador_Result> SP_MW_FicheroVisitador(Nullable<int> ciclo, Nullable<int> linea, Nullable<int> region, Nullable<long> visitador)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_FicheroVisitador_Result>("SP_MW_FicheroVisitador", cicloParameter, lineaParameter, regionParameter, visitadorParameter);
        }
    
        public virtual ObjectResult<SP_MW_HojaRutaPorReg_Result> SP_MW_HojaRutaPorReg(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_HojaRutaPorReg_Result>("SP_MW_HojaRutaPorReg", cicloParameter);
        }
    
        public virtual ObjectResult<SP_MW_HojaRutaPorRegLin_Result> SP_MW_HojaRutaPorRegLin(Nullable<int> ciclo, Nullable<int> region)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_HojaRutaPorRegLin_Result>("SP_MW_HojaRutaPorRegLin", cicloParameter, regionParameter);
        }
    
        public virtual ObjectResult<SP_MW_HojaRutaPorRegLinVis_Result> SP_MW_HojaRutaPorRegLinVis(Nullable<int> ciclo, Nullable<int> region, Nullable<int> linea)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_HojaRutaPorRegLinVis_Result>("SP_MW_HojaRutaPorRegLinVis", cicloParameter, regionParameter, lineaParameter);
        }
    
        public virtual ObjectResult<SP_MW_HojaRutaPorRegLinVisDetalle_Result> SP_MW_HojaRutaPorRegLinVisDetalle(Nullable<int> ciclo, Nullable<int> visitador)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_HojaRutaPorRegLinVisDetalle_Result>("SP_MW_HojaRutaPorRegLinVisDetalle", cicloParameter, visitadorParameter);
        }
    
        public virtual ObjectResult<SP_MW_HojaRutaPorRegLinVisRutas_Result> SP_MW_HojaRutaPorRegLinVisRutas(Nullable<int> ciclo, Nullable<int> visitador)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_HojaRutaPorRegLinVisRutas_Result>("SP_MW_HojaRutaPorRegLinVisRutas", cicloParameter, visitadorParameter);
        }
    
        public virtual int SP_MW_LoadAprobaciones(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MW_LoadAprobaciones", usuarioParameter);
        }
    
        public virtual ObjectResult<SP_MW_Marcas_EsqPro_Result> SP_MW_Marcas_EsqPro(Nullable<int> linea, Nullable<int> especialidad, Nullable<int> ciclo)
        {
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var especialidadParameter = especialidad.HasValue ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(int));
    
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Marcas_EsqPro_Result>("SP_MW_Marcas_EsqPro", lineaParameter, especialidadParameter, cicloParameter);
        }
    
        public virtual ObjectResult<SP_MW_Marcas_MarCom_Result> SP_MW_Marcas_MarCom(Nullable<int> marca)
        {
            var marcaParameter = marca.HasValue ?
                new ObjectParameter("marca", marca) :
                new ObjectParameter("marca", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Marcas_MarCom_Result>("SP_MW_Marcas_MarCom", marcaParameter);
        }
    
        public virtual ObjectResult<SP_MW_Posiciones_EsqPro_Result> SP_MW_Posiciones_EsqPro(Nullable<int> ciclo, Nullable<int> linea, Nullable<int> especialidad)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var especialidadParameter = especialidad.HasValue ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Posiciones_EsqPro_Result>("SP_MW_Posiciones_EsqPro", cicloParameter, lineaParameter, especialidadParameter);
        }
    
        public virtual int SP_MW_SetAprobacion(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MW_SetAprobacion", usuarioParameter);
        }
    
        public virtual ObjectResult<SP_MW_Solicitudes_Result> SP_MW_Solicitudes(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Solicitudes_Result>("SP_MW_Solicitudes", cicloParameter);
        }
    
        public virtual ObjectResult<SP_MW_Transmisiones_Result> SP_MW_Transmisiones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Transmisiones_Result>("SP_MW_Transmisiones");
        }
    
        public virtual ObjectResult<SP_MW_Usuarios_FicAcc_Result> SP_MW_Usuarios_FicAcc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Usuarios_FicAcc_Result>("SP_MW_Usuarios_FicAcc");
        }
    
        public virtual ObjectResult<SP_MW_VarFicheroAltas_Result> SP_MW_VarFicheroAltas(Nullable<int> ciclo, Nullable<int> visitador)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VarFicheroAltas_Result>("SP_MW_VarFicheroAltas", cicloParameter, visitadorParameter);
        }
    
        public virtual ObjectResult<SP_MW_VarFicheroBajas_Result> SP_MW_VarFicheroBajas(Nullable<int> ciclo, Nullable<int> visitador)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VarFicheroBajas_Result>("SP_MW_VarFicheroBajas", cicloParameter, visitadorParameter);
        }
    
        public virtual ObjectResult<SP_MW_VarFicheroPorReg_Result> SP_MW_VarFicheroPorReg(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VarFicheroPorReg_Result>("SP_MW_VarFicheroPorReg", cicloParameter);
        }
    
        public virtual ObjectResult<SP_MW_VarFicheroPorRegLin_Result> SP_MW_VarFicheroPorRegLin(Nullable<int> ciclo, Nullable<int> region)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VarFicheroPorRegLin_Result>("SP_MW_VarFicheroPorRegLin", cicloParameter, regionParameter);
        }
    
        public virtual ObjectResult<SP_MW_VarFicheroPorRegLinVis_Result> SP_MW_VarFicheroPorRegLinVis(Nullable<int> ciclo, Nullable<int> region, Nullable<int> linea)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VarFicheroPorRegLinVis_Result>("SP_MW_VarFicheroPorRegLinVis", cicloParameter, regionParameter, lineaParameter);
        }
    
        public virtual ObjectResult<SP_MW_VisFarmaciaPorReg_Result> SP_MW_VisFarmaciaPorReg(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VisFarmaciaPorReg_Result>("SP_MW_VisFarmaciaPorReg", cicloParameter);
        }
    
        public virtual ObjectResult<SP_MW_VisFarmaciaPorRegLin_Result> SP_MW_VisFarmaciaPorRegLin(Nullable<int> ciclo, Nullable<int> region)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VisFarmaciaPorRegLin_Result>("SP_MW_VisFarmaciaPorRegLin", cicloParameter, regionParameter);
        }
    
        public virtual ObjectResult<SP_MW_VisFarmaciaPorRegLinVis_Result> SP_MW_VisFarmaciaPorRegLinVis(Nullable<int> ciclo, Nullable<int> region, Nullable<int> linea)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VisFarmaciaPorRegLinVis_Result>("SP_MW_VisFarmaciaPorRegLinVis", cicloParameter, regionParameter, lineaParameter);
        }
    
        public virtual ObjectResult<SP_MW_VisFarmaciaPorRegLinVisFar_Result> SP_MW_VisFarmaciaPorRegLinVisFar(Nullable<int> ciclo, Nullable<int> region, Nullable<int> linea, Nullable<int> visitador)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VisFarmaciaPorRegLinVisFar_Result>("SP_MW_VisFarmaciaPorRegLinVisFar", cicloParameter, regionParameter, lineaParameter, visitadorParameter);
        }
    
        public virtual ObjectResult<SP_MW_VisHospitalPorReg_Result> SP_MW_VisHospitalPorReg(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VisHospitalPorReg_Result>("SP_MW_VisHospitalPorReg", cicloParameter);
        }
    
        public virtual ObjectResult<SP_MW_VisHospitalPorRegLin_Result> SP_MW_VisHospitalPorRegLin(Nullable<int> ciclo, Nullable<int> region)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VisHospitalPorRegLin_Result>("SP_MW_VisHospitalPorRegLin", cicloParameter, regionParameter);
        }
    
        public virtual ObjectResult<SP_MW_VisHospitalPorRegLinVis_Result> SP_MW_VisHospitalPorRegLinVis(Nullable<int> ciclo, Nullable<int> region, Nullable<int> linea)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VisHospitalPorRegLinVis_Result>("SP_MW_VisHospitalPorRegLinVis", cicloParameter, regionParameter, lineaParameter);
        }
    
        public virtual ObjectResult<SP_MW_VisHospitalPorRegLinVisHos_Result> SP_MW_VisHospitalPorRegLinVisHos(Nullable<int> ciclo, Nullable<int> region, Nullable<int> linea, Nullable<int> visitador)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VisHospitalPorRegLinVisHos_Result>("SP_MW_VisHospitalPorRegLinVisHos", cicloParameter, regionParameter, lineaParameter, visitadorParameter);
        }
    
        public virtual ObjectResult<SP_MW_Visitadores_Result> SP_MW_Visitadores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Visitadores_Result>("SP_MW_Visitadores");
        }
    
        public virtual ObjectResult<SP_MW_Visitadores_FicVis_Result> SP_MW_Visitadores_FicVis(Nullable<int> ciclo, Nullable<int> linea, Nullable<int> region)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Visitadores_FicVis_Result>("SP_MW_Visitadores_FicVis", cicloParameter, lineaParameter, regionParameter);
        }
    
        public virtual ObjectResult<SP_MW_Visitadores_VisMed_Result> SP_MW_Visitadores_VisMed(Nullable<int> ciclo, Nullable<int> linea, Nullable<int> region)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Visitadores_VisMed_Result>("SP_MW_Visitadores_VisMed", cicloParameter, lineaParameter, regionParameter);
        }
    
        public virtual ObjectResult<SP_MW_VisitadoresHistorial_Apr_Result> SP_MW_VisitadoresHistorial_Apr()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VisitadoresHistorial_Apr_Result>("SP_MW_VisitadoresHistorial_Apr");
        }
    
        public virtual ObjectResult<SP_MW_VisMedicos_Result> SP_MW_VisMedicos(Nullable<int> ciclo, Nullable<int> linea, Nullable<int> region, Nullable<int> visitador)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VisMedicos_Result>("SP_MW_VisMedicos", cicloParameter, lineaParameter, regionParameter, visitadorParameter);
        }
    
        public virtual ObjectResult<SP_MW_Zonas_HisVis_Result> SP_MW_Zonas_HisVis(Nullable<int> region, Nullable<int> linea)
        {
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Zonas_HisVis_Result>("SP_MW_Zonas_HisVis", regionParameter, lineaParameter);
        }
    
        public virtual ObjectResult<SP_MW_Zonas_Zon_Result> SP_MW_Zonas_Zon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Zonas_Zon_Result>("SP_MW_Zonas_Zon");
        }
    
        public virtual ObjectResult<SP_MWS_ConfigDistribucion_ConDis_Result> SP_MWS_ConfigDistribucion_ConDis(Nullable<int> articulo, string lineas, string especialidades)
        {
            var articuloParameter = articulo.HasValue ?
                new ObjectParameter("articulo", articulo) :
                new ObjectParameter("articulo", typeof(int));
    
            var lineasParameter = lineas != null ?
                new ObjectParameter("lineas", lineas) :
                new ObjectParameter("lineas", typeof(string));
    
            var especialidadesParameter = especialidades != null ?
                new ObjectParameter("especialidades", especialidades) :
                new ObjectParameter("especialidades", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_ConfigDistribucion_ConDis_Result>("SP_MWS_ConfigDistribucion_ConDis", articuloParameter, lineasParameter, especialidadesParameter);
        }
    
        public virtual ObjectResult<SP_MWS_GetNoContFichero_ConDis_Result> SP_MWS_GetNoContFichero_ConDis(Nullable<int> articulo)
        {
            var articuloParameter = articulo.HasValue ?
                new ObjectParameter("articulo", articulo) :
                new ObjectParameter("articulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_GetNoContFichero_ConDis_Result>("SP_MWS_GetNoContFichero_ConDis", articuloParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_MWS_InvPosDispensado_ConDis(Nullable<int> articulo, string lineas, string especialidades, Nullable<int> nF)
        {
            var articuloParameter = articulo.HasValue ?
                new ObjectParameter("articulo", articulo) :
                new ObjectParameter("articulo", typeof(int));
    
            var lineasParameter = lineas != null ?
                new ObjectParameter("lineas", lineas) :
                new ObjectParameter("lineas", typeof(string));
    
            var especialidadesParameter = especialidades != null ?
                new ObjectParameter("especialidades", especialidades) :
                new ObjectParameter("especialidades", typeof(string));
    
            var nFParameter = nF.HasValue ?
                new ObjectParameter("NF", nF) :
                new ObjectParameter("NF", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_MWS_InvPosDispensado_ConDis", articuloParameter, lineasParameter, especialidadesParameter, nFParameter);
        }
    
        public virtual ObjectResult<SP_MWS_Lineas_ConDis_Result> SP_MWS_Lineas_ConDis(Nullable<int> marca)
        {
            var marcaParameter = marca.HasValue ?
                new ObjectParameter("marca", marca) :
                new ObjectParameter("marca", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_Lineas_ConDis_Result>("SP_MWS_Lineas_ConDis", marcaParameter);
        }
    
        public virtual int SP_MWS_LoadConfigDistribucion(Nullable<int> articulo, string lineas, string especialidades)
        {
            var articuloParameter = articulo.HasValue ?
                new ObjectParameter("articulo", articulo) :
                new ObjectParameter("articulo", typeof(int));
    
            var lineasParameter = lineas != null ?
                new ObjectParameter("lineas", lineas) :
                new ObjectParameter("lineas", typeof(string));
    
            var especialidadesParameter = especialidades != null ?
                new ObjectParameter("especialidades", especialidades) :
                new ObjectParameter("especialidades", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWS_LoadConfigDistribucion", articuloParameter, lineasParameter, especialidadesParameter);
        }
    
        public virtual int SP_MWS_LoadNotaEntregaCAB_ConDis(string lineas, string especialidades)
        {
            var lineasParameter = lineas != null ?
                new ObjectParameter("lineas", lineas) :
                new ObjectParameter("lineas", typeof(string));
    
            var especialidadesParameter = especialidades != null ?
                new ObjectParameter("especialidades", especialidades) :
                new ObjectParameter("especialidades", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWS_LoadNotaEntregaCAB_ConDis", lineasParameter, especialidadesParameter);
        }
    
        public virtual int SP_MWS_LoadNotaEntregaDET_ConDis(Nullable<int> articulo, string lineas, string especialidades, Nullable<int> nF)
        {
            var articuloParameter = articulo.HasValue ?
                new ObjectParameter("articulo", articulo) :
                new ObjectParameter("articulo", typeof(int));
    
            var lineasParameter = lineas != null ?
                new ObjectParameter("lineas", lineas) :
                new ObjectParameter("lineas", typeof(string));
    
            var especialidadesParameter = especialidades != null ?
                new ObjectParameter("especialidades", especialidades) :
                new ObjectParameter("especialidades", typeof(string));
    
            var nFParameter = nF.HasValue ?
                new ObjectParameter("NF", nF) :
                new ObjectParameter("NF", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWS_LoadNotaEntregaDET_ConDis", articuloParameter, lineasParameter, especialidadesParameter, nFParameter);
        }
    
        public virtual ObjectResult<SP_MWS_Marcas_ConDis_Result> SP_MWS_Marcas_ConDis(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_Marcas_ConDis_Result>("SP_MWS_Marcas_ConDis", usuarioParameter);
        }
    
        public virtual ObjectResult<SP_MWS_PreDispensado_ConDis_Result> SP_MWS_PreDispensado_ConDis(Nullable<int> articulo, string lineas, string especialidades, Nullable<int> nF)
        {
            var articuloParameter = articulo.HasValue ?
                new ObjectParameter("articulo", articulo) :
                new ObjectParameter("articulo", typeof(int));
    
            var lineasParameter = lineas != null ?
                new ObjectParameter("lineas", lineas) :
                new ObjectParameter("lineas", typeof(string));
    
            var especialidadesParameter = especialidades != null ?
                new ObjectParameter("especialidades", especialidades) :
                new ObjectParameter("especialidades", typeof(string));
    
            var nFParameter = nF.HasValue ?
                new ObjectParameter("NF", nF) :
                new ObjectParameter("NF", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_PreDispensado_ConDis_Result>("SP_MWS_PreDispensado_ConDis", articuloParameter, lineasParameter, especialidadesParameter, nFParameter);
        }
    
        public virtual int SP_MWS_SetNoContFichero_ConDis(Nullable<int> articulo, Nullable<int> nuNF)
        {
            var articuloParameter = articulo.HasValue ?
                new ObjectParameter("articulo", articulo) :
                new ObjectParameter("articulo", typeof(int));
    
            var nuNFParameter = nuNF.HasValue ?
                new ObjectParameter("nuNF", nuNF) :
                new ObjectParameter("nuNF", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWS_SetNoContFichero_ConDis", articuloParameter, nuNFParameter);
        }
    
        public virtual ObjectResult<SP_MWS_VisitadoresHistorial_ConDis_Result> SP_MWS_VisitadoresHistorial_ConDis(string lineas, string especialidades)
        {
            var lineasParameter = lineas != null ?
                new ObjectParameter("lineas", lineas) :
                new ObjectParameter("lineas", typeof(string));
    
            var especialidadesParameter = especialidades != null ?
                new ObjectParameter("especialidades", especialidades) :
                new ObjectParameter("especialidades", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_VisitadoresHistorial_ConDis_Result>("SP_MWS_VisitadoresHistorial_ConDis", lineasParameter, especialidadesParameter);
        }
    
        public virtual int SP_MWS_DeleteConfigDistribucion_ConDis(Nullable<int> articulo, string lineas, string especialidades)
        {
            var articuloParameter = articulo.HasValue ?
                new ObjectParameter("articulo", articulo) :
                new ObjectParameter("articulo", typeof(int));
    
            var lineasParameter = lineas != null ?
                new ObjectParameter("lineas", lineas) :
                new ObjectParameter("lineas", typeof(string));
    
            var especialidadesParameter = especialidades != null ?
                new ObjectParameter("especialidades", especialidades) :
                new ObjectParameter("especialidades", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWS_DeleteConfigDistribucion_ConDis", articuloParameter, lineasParameter, especialidadesParameter);
        }
    
        public virtual int SP_MWS_SetNotaEntregaCAB_ValVis(Nullable<long> visitadoresHistorial, Nullable<bool> boActivo)
        {
            var visitadoresHistorialParameter = visitadoresHistorial.HasValue ?
                new ObjectParameter("visitadoresHistorial", visitadoresHistorial) :
                new ObjectParameter("visitadoresHistorial", typeof(long));
    
            var boActivoParameter = boActivo.HasValue ?
                new ObjectParameter("boActivo", boActivo) :
                new ObjectParameter("boActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWS_SetNotaEntregaCAB_ValVis", visitadoresHistorialParameter, boActivoParameter);
        }
    
        public virtual ObjectResult<SP_MWS_ResumenCierreDistribucion_CieDis_Result> SP_MWS_ResumenCierreDistribucion_CieDis(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_ResumenCierreDistribucion_CieDis_Result>("SP_MWS_ResumenCierreDistribucion_CieDis", usuarioParameter);
        }
    
        public virtual int SP_MWS_SetCierreDistribucion_CieDis(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWS_SetCierreDistribucion_CieDis", usuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_MWS_GetCierreDist_CieDis(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_MWS_GetCierreDist_CieDis", usuarioParameter);
        }
    
        public virtual ObjectResult<SP_MWS_CierreDistribucion_DisCer_Result> SP_MWS_CierreDistribucion_DisCer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_CierreDistribucion_DisCer_Result>("SP_MWS_CierreDistribucion_DisCer");
        }
    
        public virtual ObjectResult<SP_MWS_ResumenDistribuciones_AprDis_Result> SP_MWS_ResumenDistribuciones_AprDis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_ResumenDistribuciones_AprDis_Result>("SP_MWS_ResumenDistribuciones_AprDis");
        }
    
        public virtual int SP_MWS_DeleteDistArticulo_AprDis(Nullable<int> articulo)
        {
            var articuloParameter = articulo.HasValue ?
                new ObjectParameter("articulo", articulo) :
                new ObjectParameter("articulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWS_DeleteDistArticulo_AprDis", articuloParameter);
        }
    
        public virtual int SP_MWS_SetAprDistribucion_AprDis(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWS_SetAprDistribucion_AprDis", usuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_MWS_GetAprDistribucion_AprDis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_MWS_GetAprDistribucion_AprDis");
        }
    
        public virtual ObjectResult<SP_MWS_Especialidades_ConDis_Result> SP_MWS_Especialidades_ConDis(string lineas)
        {
            var lineasParameter = lineas != null ?
                new ObjectParameter("lineas", lineas) :
                new ObjectParameter("lineas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_Especialidades_ConDis_Result>("SP_MWS_Especialidades_ConDis", lineasParameter);
        }
    
        public virtual ObjectResult<SP_MW_Dashboard_CoberturaPorReg_Result> SP_MW_Dashboard_CoberturaPorReg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Dashboard_CoberturaPorReg_Result>("SP_MW_Dashboard_CoberturaPorReg");
        }
    
        public virtual ObjectResult<SP_MWS_CiclosDispensados_NotEnt_Result> SP_MWS_CiclosDispensados_NotEnt()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_CiclosDispensados_NotEnt_Result>("SP_MWS_CiclosDispensados_NotEnt");
        }
    
        public virtual ObjectResult<SP_MW_VisMedicosDetalle_Result> SP_MW_VisMedicosDetalle(Nullable<int> ciclo, Nullable<int> visitador, string registro)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            var registroParameter = registro != null ?
                new ObjectParameter("registro", registro) :
                new ObjectParameter("registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VisMedicosDetalle_Result>("SP_MW_VisMedicosDetalle", cicloParameter, visitadorParameter, registroParameter);
        }
    
        public virtual ObjectResult<SP_MWS_SalidaTxtSIDEX_Result> SP_MWS_SalidaTxtSIDEX(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_SalidaTxtSIDEX_Result>("SP_MWS_SalidaTxtSIDEX", cicloParameter);
        }
    
        public virtual ObjectResult<string> SP_MWS_SalidaXmlSIDEX(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_MWS_SalidaXmlSIDEX", cicloParameter);
        }
    
        public virtual ObjectResult<SP_MWS_Existencias_ConDis_Result> SP_MWS_Existencias_ConDis(Nullable<int> articulo)
        {
            var articuloParameter = articulo.HasValue ?
                new ObjectParameter("articulo", articulo) :
                new ObjectParameter("articulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_Existencias_ConDis_Result>("SP_MWS_Existencias_ConDis", articuloParameter);
        }
    
        public virtual ObjectResult<SP_MWS_ArticulosDistribucion_AprDis_Result> SP_MWS_ArticulosDistribucion_AprDis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_ArticulosDistribucion_AprDis_Result>("SP_MWS_ArticulosDistribucion_AprDis");
        }
    
        public virtual ObjectResult<SP_MW_VisitadoresAltasBajas_Result> SP_MW_VisitadoresAltasBajas(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_VisitadoresAltasBajas_Result>("SP_MW_VisitadoresAltasBajas", idUsuarioParameter);
        }
    
        public virtual int SP_MW_UpdateAltas(string clasificacion, string especialidad, string estatus, string zona, string nroSanitario)
        {
            var clasificacionParameter = clasificacion != null ?
                new ObjectParameter("clasificacion", clasificacion) :
                new ObjectParameter("clasificacion", typeof(string));
    
            var especialidadParameter = especialidad != null ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(string));
    
            var estatusParameter = estatus != null ?
                new ObjectParameter("estatus", estatus) :
                new ObjectParameter("estatus", typeof(string));
    
            var zonaParameter = zona != null ?
                new ObjectParameter("zona", zona) :
                new ObjectParameter("zona", typeof(string));
    
            var nroSanitarioParameter = nroSanitario != null ?
                new ObjectParameter("nroSanitario", nroSanitario) :
                new ObjectParameter("nroSanitario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MW_UpdateAltas", clasificacionParameter, especialidadParameter, estatusParameter, zonaParameter, nroSanitarioParameter);
        }
    
        public virtual int SP_MW_UpdateBajas(string clave, string eliminado, string zona, Nullable<int> registro)
        {
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var eliminadoParameter = eliminado != null ?
                new ObjectParameter("eliminado", eliminado) :
                new ObjectParameter("eliminado", typeof(string));
    
            var zonaParameter = zona != null ?
                new ObjectParameter("zona", zona) :
                new ObjectParameter("zona", typeof(string));
    
            var registroParameter = registro.HasValue ?
                new ObjectParameter("registro", registro) :
                new ObjectParameter("registro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MW_UpdateBajas", claveParameter, eliminadoParameter, zonaParameter, registroParameter);
        }
    
        public virtual ObjectResult<SP_MW_Usuarios_AltBaj_Result> SP_MW_Usuarios_AltBaj(Nullable<int> visitador)
        {
            var visitadorParameter = visitador.HasValue ?
                new ObjectParameter("visitador", visitador) :
                new ObjectParameter("visitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Usuarios_AltBaj_Result>("SP_MW_Usuarios_AltBaj", visitadorParameter);
        }
    
        public virtual ObjectResult<SP_MW_DrogueriasAlmacenes_DroPro_Result> SP_MW_DrogueriasAlmacenes_DroPro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_DrogueriasAlmacenes_DroPro_Result>("SP_MW_DrogueriasAlmacenes_DroPro");
        }
    
        public virtual ObjectResult<SP_MW_Aprobaciones_Apr_Result> SP_MW_Aprobaciones_Apr(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Aprobaciones_Apr_Result>("SP_MW_Aprobaciones_Apr", usuarioParameter);
        }
    
        public virtual ObjectResult<SP_MW_AprobacionAltas_Result> SP_MW_AprobacionAltas(Nullable<int> idVisitador)
        {
            var idVisitadorParameter = idVisitador.HasValue ?
                new ObjectParameter("idVisitador", idVisitador) :
                new ObjectParameter("idVisitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_AprobacionAltas_Result>("SP_MW_AprobacionAltas", idVisitadorParameter);
        }
    
        public virtual ObjectResult<SP_MW_AprobacionBajas_Result> SP_MW_AprobacionBajas(Nullable<int> idVisitador)
        {
            var idVisitadorParameter = idVisitador.HasValue ?
                new ObjectParameter("idVisitador", idVisitador) :
                new ObjectParameter("idVisitador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_AprobacionBajas_Result>("SP_MW_AprobacionBajas", idVisitadorParameter);
        }
    
        public virtual ObjectResult<SP_MWS_Articulos_CieDis_Result> SP_MWS_Articulos_CieDis(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_Articulos_CieDis_Result>("SP_MWS_Articulos_CieDis", usuarioParameter);
        }
    
        public virtual ObjectResult<SP_MWS_NotaEntregaDetalle_NotEnt_Result> SP_MWS_NotaEntregaDetalle_NotEnt(Nullable<long> notaEntrega)
        {
            var notaEntregaParameter = notaEntrega.HasValue ?
                new ObjectParameter("notaEntrega", notaEntrega) :
                new ObjectParameter("notaEntrega", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_NotaEntregaDetalle_NotEnt_Result>("SP_MWS_NotaEntregaDetalle_NotEnt", notaEntregaParameter);
        }
    
        public virtual ObjectResult<SP_MWS_NotaEntregaConsolidado_NotEntCon_Result> SP_MWS_NotaEntregaConsolidado_NotEntCon(Nullable<int> ciclo)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_NotaEntregaConsolidado_NotEntCon_Result>("SP_MWS_NotaEntregaConsolidado_NotEntCon", cicloParameter);
        }
    
        public virtual ObjectResult<SP_MWS_ValidaVisitadores_ValVis_Result> SP_MWS_ValidaVisitadores_ValVis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWS_ValidaVisitadores_ValVis_Result>("SP_MWS_ValidaVisitadores_ValVis");
        }
    }
}
