//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Aprobaciones
    {
        public long ID_Aprobacion { get; set; }
        public short ID_Ciclo { get; set; }
        public short ID_Region { get; set; }
        public short ID_Linea { get; set; }
        public bool BO_CierreCiclo { get; set; }
        public long ID_VisitadoresHistorial { get; set; }
        public System.DateTime FE_Transmision { get; set; }
        public decimal NU_PorcentajeVisita { get; set; }
        public decimal NU_PorcentajeRevisita { get; set; }
        public decimal NU_MIX { get; set; }
        public decimal NU_PDR { get; set; }
        public decimal NU_PP { get; set; }
        public int NU_AltasAprob { get; set; }
        public int NU_BajasAprob { get; set; }
        public decimal NU_PorcentajeVisitaFarmacia { get; set; }
        public decimal NU_PorcentajeVisitaHospital { get; set; }
        public decimal NU_DCS { get; set; }
        public decimal NU_DCN { get; set; }
        public decimal NU_DVN { get; set; }
        public decimal NU_Total { get; set; }
        public decimal NU_Ajuste { get; set; }
        public string TX_Observacion { get; set; }
    
        public virtual MW_Ciclos MW_Ciclos { get; set; }
        public virtual MW_VisitadoresHistorial MW_VisitadoresHistorial { get; set; }
        public virtual MW_Lineas MW_Lineas { get; set; }
        public virtual MW_Regiones MW_Regiones { get; set; }
    }
}
