//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_BeneficioVisitas
    {
        public short ID_Beneficio { get; set; }
        public string TX_Beneficio { get; set; }
        public bool BO_Activo { get; set; }
    }
}
