//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_ClasificacionMedicos
    {
        public MW_ClasificacionMedicos()
        {
            this.MWS_ConfigDistribucion = new HashSet<MWS_ConfigDistribucion>();
            this.MWS_FicheroEspejo = new HashSet<MWS_FicheroEspejo>();
        }
    
        public short ID_Clasificacion { get; set; }
        public string TX_Clasificacion { get; set; }
        public short NU_Puntaje { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MWS_ConfigDistribucion> MWS_ConfigDistribucion { get; set; }
        public virtual ICollection<MWS_FicheroEspejo> MWS_FicheroEspejo { get; set; }
    }
}
