//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Ciclos
    {
        public MW_Ciclos()
        {
            this.MW_ActivEspeciales = new HashSet<MW_ActivEspeciales>();
            this.MW_ActivEspeciales1 = new HashSet<MW_ActivEspeciales>();
            this.MW_Aprobaciones = new HashSet<MW_Aprobaciones>();
            this.MW_EsquemasPromocionales = new HashSet<MW_EsquemasPromocionales>();
            this.MW_LineasEspecialidades = new HashSet<MW_LineasEspecialidades>();
            this.MW_LineasEspecialidades1 = new HashSet<MW_LineasEspecialidades>();
            this.MW_MarcasLineas = new HashSet<MW_MarcasLineas>();
            this.MW_MarcasLineas1 = new HashSet<MW_MarcasLineas>();
            this.MWS_CargaInv = new HashSet<MWS_CargaInv>();
            this.MWS_ConfigDistribucion = new HashSet<MWS_ConfigDistribucion>();
            this.MWS_FicheroEspejo = new HashSet<MWS_FicheroEspejo>();
            this.MWS_FicheroEspejo1 = new HashSet<MWS_FicheroEspejo>();
            this.MW_Umbrales = new HashSet<MW_Umbrales>();
            this.MW_Umbrales1 = new HashSet<MW_Umbrales>();
            this.MWS_NoContFichero = new HashSet<MWS_NoContFichero>();
            this.MWS_NotaEntregaCabecera = new HashSet<MWS_NotaEntregaCabecera>();
            this.MW_VisitadoresHistorial = new HashSet<MW_VisitadoresHistorial>();
            this.MW_VisitadoresHistorial1 = new HashSet<MW_VisitadoresHistorial>();
            this.MW_AprobacionesUsuarios = new HashSet<MW_AprobacionesUsuarios>();
            this.MW_DescuentosUsuarios = new HashSet<MW_DescuentosUsuarios>();
            this.MW_UsuariosResponsabilidades = new HashSet<MW_UsuariosResponsabilidades>();
            this.MW_UsuariosResponsabilidades1 = new HashSet<MW_UsuariosResponsabilidades>();
            this.MWS_UsuarioAprobacion = new HashSet<MWS_UsuarioAprobacion>();
            this.MWS_UsuarioDispensado = new HashSet<MWS_UsuarioDispensado>();
            this.MWS_ValidaVisitadores = new HashSet<MWS_ValidaVisitadores>();
            this.MWS_CierreDistribucion = new HashSet<MWS_CierreDistribucion>();
            this.MWS_AprDistribucion = new HashSet<MWS_AprDistribucion>();
            this.MWS_Existencias = new HashSet<MWS_Existencias>();
        }
    
        public short ID_Ciclo { get; set; }
        public short NU_Ano { get; set; }
        public short NU_Ciclo { get; set; }
        public System.DateTime FE_CicloIni { get; set; }
        public System.DateTime FE_CicloFin { get; set; }
        public System.DateTime FE_CicloProrroga { get; set; }
        public short NU_DiasCancelarVehiculo { get; set; }
        public short NU_DiasHabiles { get; set; }
        public Nullable<System.DateTime> FE_CargaInv { get; set; }
        public Nullable<System.DateTime> FE_IniDistribucion { get; set; }
        public Nullable<System.DateTime> FE_FinDistribucion { get; set; }
        public short NU_Estatus { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_ActivEspeciales> MW_ActivEspeciales { get; set; }
        public virtual ICollection<MW_ActivEspeciales> MW_ActivEspeciales1 { get; set; }
        public virtual ICollection<MW_Aprobaciones> MW_Aprobaciones { get; set; }
        public virtual ICollection<MW_EsquemasPromocionales> MW_EsquemasPromocionales { get; set; }
        public virtual ICollection<MW_LineasEspecialidades> MW_LineasEspecialidades { get; set; }
        public virtual ICollection<MW_LineasEspecialidades> MW_LineasEspecialidades1 { get; set; }
        public virtual ICollection<MW_MarcasLineas> MW_MarcasLineas { get; set; }
        public virtual ICollection<MW_MarcasLineas> MW_MarcasLineas1 { get; set; }
        public virtual ICollection<MWS_CargaInv> MWS_CargaInv { get; set; }
        public virtual ICollection<MWS_ConfigDistribucion> MWS_ConfigDistribucion { get; set; }
        public virtual ICollection<MWS_FicheroEspejo> MWS_FicheroEspejo { get; set; }
        public virtual ICollection<MWS_FicheroEspejo> MWS_FicheroEspejo1 { get; set; }
        public virtual ICollection<MW_Umbrales> MW_Umbrales { get; set; }
        public virtual ICollection<MW_Umbrales> MW_Umbrales1 { get; set; }
        public virtual ICollection<MWS_NoContFichero> MWS_NoContFichero { get; set; }
        public virtual ICollection<MWS_NotaEntregaCabecera> MWS_NotaEntregaCabecera { get; set; }
        public virtual ICollection<MW_VisitadoresHistorial> MW_VisitadoresHistorial { get; set; }
        public virtual ICollection<MW_VisitadoresHistorial> MW_VisitadoresHistorial1 { get; set; }
        public virtual ICollection<MW_AprobacionesUsuarios> MW_AprobacionesUsuarios { get; set; }
        public virtual ICollection<MW_DescuentosUsuarios> MW_DescuentosUsuarios { get; set; }
        public virtual ICollection<MW_UsuariosResponsabilidades> MW_UsuariosResponsabilidades { get; set; }
        public virtual ICollection<MW_UsuariosResponsabilidades> MW_UsuariosResponsabilidades1 { get; set; }
        public virtual ICollection<MWS_UsuarioAprobacion> MWS_UsuarioAprobacion { get; set; }
        public virtual ICollection<MWS_UsuarioDispensado> MWS_UsuarioDispensado { get; set; }
        public virtual ICollection<MWS_ValidaVisitadores> MWS_ValidaVisitadores { get; set; }
        public virtual ICollection<MWS_CierreDistribucion> MWS_CierreDistribucion { get; set; }
        public virtual ICollection<MWS_AprDistribucion> MWS_AprDistribucion { get; set; }
        public virtual ICollection<MWS_Existencias> MWS_Existencias { get; set; }
    }
}
