//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_ConceptoDescuentos
    {
        public MW_ConceptoDescuentos()
        {
            this.MW_DescuentosUsuarios = new HashSet<MW_DescuentosUsuarios>();
        }
    
        public short ID_ConceptoDescuento { get; set; }
        public string TX_ConceptoDescuento { get; set; }
        public bool BO_AplicaVehiculo { get; set; }
        public bool BO_AplicaCobertura { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_DescuentosUsuarios> MW_DescuentosUsuarios { get; set; }
    }
}
