//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_CadenaFarmacias
    {
        public MW_CadenaFarmacias()
        {
            this.MW_Farmacias = new HashSet<MW_Farmacias>();
        }
    
        public short ID_Cadena { get; set; }
        public string TX_Cadena { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_Farmacias> MW_Farmacias { get; set; }
    }
}
