//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Cargos
    {
        public MW_Cargos()
        {
            this.MW_Usuarios = new HashSet<MW_Usuarios>();
        }
    
        public short ID_Cargo { get; set; }
        public string TX_Cargo { get; set; }
        public bool BO_Visita { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_Usuarios> MW_Usuarios { get; set; }
    }
}
