//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_DescuentosUsuarios
    {
        public int ID_DescuentosUsuarios { get; set; }
        public short ID_Ciclo { get; set; }
        public int ID_Usuario { get; set; }
        public short ID_ConceptoDescuento { get; set; }
        public System.DateTime FE_DescuentoIni { get; set; }
        public System.DateTime FE_DescuentoFin { get; set; }
        public bool BO_MedioDia { get; set; }
        public decimal NU_TotalDescuento { get; set; }
        public string TX_Comentario { get; set; }
    
        public virtual MW_Ciclos MW_Ciclos { get; set; }
        public virtual MW_ConceptoDescuentos MW_ConceptoDescuentos { get; set; }
        public virtual MW_Usuarios MW_Usuarios { get; set; }
    }
}
