//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Droguerias
    {
        public MW_Droguerias()
        {
            this.MW_DrogueriasAlmacenes = new HashSet<MW_DrogueriasAlmacenes>();
            this.MW_LaboratoriosDroguerias = new HashSet<MW_LaboratoriosDroguerias>();
        }
    
        public short ID_Drogueria { get; set; }
        public string TX_Drogueria { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_DrogueriasAlmacenes> MW_DrogueriasAlmacenes { get; set; }
        public virtual ICollection<MW_LaboratoriosDroguerias> MW_LaboratoriosDroguerias { get; set; }
    }
}
