//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_DrogueriasAlmacenes
    {
        public MW_DrogueriasAlmacenes()
        {
            this.MW_DrogueriasProductos = new HashSet<MW_DrogueriasProductos>();
        }
    
        public short ID_DrogueriaAlmacen { get; set; }
        public short ID_Drogueria { get; set; }
        public string TX_Almacen { get; set; }
        public string TX_IDAlmacen { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual MW_Droguerias MW_Droguerias { get; set; }
        public virtual ICollection<MW_DrogueriasProductos> MW_DrogueriasProductos { get; set; }
    }
}
