//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_DrogueriasProductos
    {
        public int ID_DrogueriaProducto { get; set; }
        public short ID_DrogueriaAlmacen { get; set; }
        public Nullable<short> ID_Producto { get; set; }
        public string TX_IDProductoDrogueria { get; set; }
        public string TX_ProductoDrogueria { get; set; }
        public decimal NU_PrecioProducto { get; set; }
        public int NU_InvProducto { get; set; }
        public string TX_DrogueriaRef1 { get; set; }
        public string TX_DrogueriaRef2 { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual MW_DrogueriasAlmacenes MW_DrogueriasAlmacenes { get; set; }
        public virtual MW_Productos MW_Productos { get; set; }
    }
}
