//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Especialidades
    {
        public MW_Especialidades()
        {
            this.MW_LineasEspecialidades = new HashSet<MW_LineasEspecialidades>();
            this.MW_EsquemasPromocionales = new HashSet<MW_EsquemasPromocionales>();
            this.MWS_ConfigDistribucion = new HashSet<MWS_ConfigDistribucion>();
            this.MWS_FicheroEspejo = new HashSet<MWS_FicheroEspejo>();
        }
    
        public short ID_Especialidad { get; set; }
        public string TX_Especialidad { get; set; }
        public string TX_EspecialidadAbr { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_LineasEspecialidades> MW_LineasEspecialidades { get; set; }
        public virtual ICollection<MW_EsquemasPromocionales> MW_EsquemasPromocionales { get; set; }
        public virtual ICollection<MWS_ConfigDistribucion> MWS_ConfigDistribucion { get; set; }
        public virtual ICollection<MWS_FicheroEspejo> MWS_FicheroEspejo { get; set; }
    }
}
