//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Farmacias
    {
        public short ID_Farmacia { get; set; }
        public string TX_Farmacia { get; set; }
        public string TX_Rif { get; set; }
        public short ID_Estado { get; set; }
        public short ID_Brick { get; set; }
        public string TX_Ruta { get; set; }
        public string TX_Direccion { get; set; }
        public string TX_Telefono1 { get; set; }
        public string TX_Telefono2 { get; set; }
        public short ID_Cadena { get; set; }
        public short ID_Clasificacion { get; set; }
        public System.DateTime FE_Registro { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual MW_CadenaFarmacias MW_CadenaFarmacias { get; set; }
        public virtual MW_ClasificacionFarmacias MW_ClasificacionFarmacias { get; set; }
        public virtual MW_LocacionBricks MW_LocacionBricks { get; set; }
        public virtual MW_LocacionEstados MW_LocacionEstados { get; set; }
    }
}
