//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Instituciones
    {
        public MW_Instituciones()
        {
            this.MW_Hospitales = new HashSet<MW_Hospitales>();
        }
    
        public short ID_Institucion { get; set; }
        public string TX_Institucion { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_Hospitales> MW_Hospitales { get; set; }
    }
}
