//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_LaboratoriosDroguerias
    {
        public byte ID_LaboratorioDrogueria { get; set; }
        public short ID_Laboratorio { get; set; }
        public short ID_Drogueria { get; set; }
        public string TX_Ruta { get; set; }
        public string TX_Usuario { get; set; }
        public string TX_Password { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual MW_Droguerias MW_Droguerias { get; set; }
        public virtual MW_Laboratorios MW_Laboratorios { get; set; }
    }
}
