//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_LocacionPaises
    {
        public MW_LocacionPaises()
        {
            this.MW_LocacionEstados = new HashSet<MW_LocacionEstados>();
        }
    
        public short ID_Pais { get; set; }
        public string TX_Pais { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_LocacionEstados> MW_LocacionEstados { get; set; }
    }
}
