//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Lineas
    {
        public MW_Lineas()
        {
            this.MW_ActivEspeciales = new HashSet<MW_ActivEspeciales>();
            this.MW_LineasEspecialidades = new HashSet<MW_LineasEspecialidades>();
            this.MW_MarcasLineas = new HashSet<MW_MarcasLineas>();
            this.MW_EsquemasPromocionales = new HashSet<MW_EsquemasPromocionales>();
            this.MW_Zonas = new HashSet<MW_Zonas>();
            this.MWS_ConfigDistribucion = new HashSet<MWS_ConfigDistribucion>();
            this.MW_VisitadoresHistorial = new HashSet<MW_VisitadoresHistorial>();
            this.MW_UsuariosResponsabilidades = new HashSet<MW_UsuariosResponsabilidades>();
            this.MW_Aprobaciones = new HashSet<MW_Aprobaciones>();
        }
    
        public short ID_Linea { get; set; }
        public string TX_Linea { get; set; }
        public string TX_LineaAbr { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_ActivEspeciales> MW_ActivEspeciales { get; set; }
        public virtual ICollection<MW_LineasEspecialidades> MW_LineasEspecialidades { get; set; }
        public virtual ICollection<MW_MarcasLineas> MW_MarcasLineas { get; set; }
        public virtual ICollection<MW_EsquemasPromocionales> MW_EsquemasPromocionales { get; set; }
        public virtual ICollection<MW_Zonas> MW_Zonas { get; set; }
        public virtual ICollection<MWS_ConfigDistribucion> MWS_ConfigDistribucion { get; set; }
        public virtual ICollection<MW_VisitadoresHistorial> MW_VisitadoresHistorial { get; set; }
        public virtual ICollection<MW_UsuariosResponsabilidades> MW_UsuariosResponsabilidades { get; set; }
        public virtual ICollection<MW_Aprobaciones> MW_Aprobaciones { get; set; }
    }
}
