//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_LocacionBricks
    {
        public MW_LocacionBricks()
        {
            this.MW_Farmacias = new HashSet<MW_Farmacias>();
            this.MW_Hospitales = new HashSet<MW_Hospitales>();
        }
    
        public short ID_Brick { get; set; }
        public short NU_Brick { get; set; }
        public string TX_Brick { get; set; }
        public bool BO_Activo { get; set; }
        public short ID_Estado { get; set; }
    
        public virtual ICollection<MW_Farmacias> MW_Farmacias { get; set; }
        public virtual ICollection<MW_Hospitales> MW_Hospitales { get; set; }
        public virtual MW_LocacionEstados MW_LocacionEstados { get; set; }
    }
}
