//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Laboratorios
    {
        public MW_Laboratorios()
        {
            this.MW_Marcas = new HashSet<MW_Marcas>();
            this.MW_LaboratoriosDroguerias = new HashSet<MW_LaboratoriosDroguerias>();
        }
    
        public short ID_Laboratorio { get; set; }
        public string TX_Laboratorio { get; set; }
        public bool BO_LaboratorioMedinet { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_Marcas> MW_Marcas { get; set; }
        public virtual ICollection<MW_LaboratoriosDroguerias> MW_LaboratoriosDroguerias { get; set; }
    }
}
