//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Medicos
    {
        public int ID_Medico { get; set; }
        public int NU_RegistroSanitario { get; set; }
        public string TX_Nombre1 { get; set; }
        public string TX_Nombre2 { get; set; }
        public string TX_Apellido1 { get; set; }
        public string TX_Apellido2 { get; set; }
        public string TX_Sello { get; set; }
        public bool BO_Activo { get; set; }
    }
}
