//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_MarcasCompetencias
    {
        public short ID_MarcasCompentencia { get; set; }
        public short ID_Marca { get; set; }
        public short ID_Competencia { get; set; }
    
        public virtual MW_Marcas MW_Marcas { get; set; }
        public virtual MW_Marcas MW_Marcas1 { get; set; }
    }
}
