//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Marcas
    {
        public MW_Marcas()
        {
            this.MW_ActivEspeciales = new HashSet<MW_ActivEspeciales>();
            this.MW_MarcasCompetencias = new HashSet<MW_MarcasCompetencias>();
            this.MW_MarcasCompetencias1 = new HashSet<MW_MarcasCompetencias>();
            this.MW_MarcasLineas = new HashSet<MW_MarcasLineas>();
            this.MW_EsquemasPromocionales = new HashSet<MW_EsquemasPromocionales>();
            this.MW_Publicaciones = new HashSet<MW_Publicaciones>();
            this.MW_UsuariosResponsabilidades = new HashSet<MW_UsuariosResponsabilidades>();
            this.MWS_Articulos = new HashSet<MWS_Articulos>();
            this.MW_Productos = new HashSet<MW_Productos>();
            this.MWS_MarcasSIDEX = new HashSet<MWS_MarcasSIDEX>();
        }
    
        public short ID_Marca { get; set; }
        public string TX_Marca { get; set; }
        public short ID_Laboratorio { get; set; }
        public string TX_Posicionamiento { get; set; }
        public System.DateTime FE_Registro { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_ActivEspeciales> MW_ActivEspeciales { get; set; }
        public virtual MW_Laboratorios MW_Laboratorios { get; set; }
        public virtual ICollection<MW_MarcasCompetencias> MW_MarcasCompetencias { get; set; }
        public virtual ICollection<MW_MarcasCompetencias> MW_MarcasCompetencias1 { get; set; }
        public virtual ICollection<MW_MarcasLineas> MW_MarcasLineas { get; set; }
        public virtual ICollection<MW_EsquemasPromocionales> MW_EsquemasPromocionales { get; set; }
        public virtual ICollection<MW_Publicaciones> MW_Publicaciones { get; set; }
        public virtual ICollection<MW_UsuariosResponsabilidades> MW_UsuariosResponsabilidades { get; set; }
        public virtual ICollection<MWS_Articulos> MWS_Articulos { get; set; }
        public virtual ICollection<MW_Productos> MW_Productos { get; set; }
        public virtual ICollection<MWS_MarcasSIDEX> MWS_MarcasSIDEX { get; set; }
    }
}
