//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Publicaciones
    {
        public short ID_Publicacion { get; set; }
        public string TX_Publicacion { get; set; }
        public string TX_Archivo { get; set; }
        public short ID_Marca { get; set; }
        public System.DateTime FE_Registro { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual MW_Marcas MW_Marcas { get; set; }
    }
}
