//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Posiciones
    {
        public MW_Posiciones()
        {
            this.MW_EsquemasPromocionales = new HashSet<MW_EsquemasPromocionales>();
        }
    
        public short ID_Posicion { get; set; }
        public string TX_Posicion { get; set; }
        public string TX_PosicionAbr { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_EsquemasPromocionales> MW_EsquemasPromocionales { get; set; }
    }
}
