//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Productos
    {
        public MW_Productos()
        {
            this.MW_DrogueriasProductos = new HashSet<MW_DrogueriasProductos>();
        }
    
        public short ID_Producto { get; set; }
        public short ID_Marca { get; set; }
        public string TX_Producto { get; set; }
        public string TX_IDProductoCliente { get; set; }
        public string TX_ProductoDesc { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_DrogueriasProductos> MW_DrogueriasProductos { get; set; }
        public virtual MW_Marcas MW_Marcas { get; set; }
    }
}
