//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_RegionesEstados
    {
        public short ID_RegionesEstados { get; set; }
        public short ID_Region { get; set; }
        public short ID_Estado { get; set; }
    
        public virtual MW_Regiones MW_Regiones { get; set; }
        public virtual MW_LocacionEstados MW_LocacionEstados { get; set; }
    }
}
