//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Roles
    {
        public MW_Roles()
        {
            this.MW_UsuariosRoles = new HashSet<MW_UsuariosRoles>();
        }
    
        public short ID_Rol { get; set; }
        public string TX_Rol { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_UsuariosRoles> MW_UsuariosRoles { get; set; }
    }
}
