//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Regiones
    {
        public MW_Regiones()
        {
            this.MW_ConvenioFarmacias = new HashSet<MW_ConvenioFarmacias>();
            this.MW_Zonas = new HashSet<MW_Zonas>();
            this.MW_RegionesEstados = new HashSet<MW_RegionesEstados>();
            this.MW_VisitadoresHistorial = new HashSet<MW_VisitadoresHistorial>();
            this.MW_UsuariosResponsabilidades = new HashSet<MW_UsuariosResponsabilidades>();
            this.MW_Aprobaciones = new HashSet<MW_Aprobaciones>();
        }
    
        public short ID_Region { get; set; }
        public string TX_Region { get; set; }
        public string TX_RegionAbr { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_ConvenioFarmacias> MW_ConvenioFarmacias { get; set; }
        public virtual ICollection<MW_Zonas> MW_Zonas { get; set; }
        public virtual ICollection<MW_RegionesEstados> MW_RegionesEstados { get; set; }
        public virtual ICollection<MW_VisitadoresHistorial> MW_VisitadoresHistorial { get; set; }
        public virtual ICollection<MW_UsuariosResponsabilidades> MW_UsuariosResponsabilidades { get; set; }
        public virtual ICollection<MW_Aprobaciones> MW_Aprobaciones { get; set; }
    }
}
