//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Usuarios
    {
        public MW_Usuarios()
        {
            this.MW_VisitadoresHistorial = new HashSet<MW_VisitadoresHistorial>();
            this.MW_AprobacionesUsuarios = new HashSet<MW_AprobacionesUsuarios>();
            this.MW_DescuentosUsuarios = new HashSet<MW_DescuentosUsuarios>();
            this.MW_FichasAcceso = new HashSet<MW_FichasAcceso>();
            this.MW_UsuariosResponsabilidades = new HashSet<MW_UsuariosResponsabilidades>();
            this.MWS_UsuarioAprobacion = new HashSet<MWS_UsuarioAprobacion>();
            this.MWS_UsuarioDispensado = new HashSet<MWS_UsuarioDispensado>();
            this.MWS_CierreDistribucion = new HashSet<MWS_CierreDistribucion>();
            this.MWS_AprDistribucion = new HashSet<MWS_AprDistribucion>();
            this.MW_UsuariosRoles = new HashSet<MW_UsuariosRoles>();
        }
    
        public int ID_Usuario { get; set; }
        public string TX_Usuario { get; set; }
        public string TX_Clave { get; set; }
        public int NU_Cedula { get; set; }
        public string TX_Nombre { get; set; }
        public string TX_Apellido { get; set; }
        public short ID_Cargo { get; set; }
        public string TX_Email1 { get; set; }
        public string TX_Email2 { get; set; }
        public string TX_Telefono1 { get; set; }
        public string TX_Telefono2 { get; set; }
        public string TX_Direccion { get; set; }
        public short ID_Estado { get; set; }
        public string TX_Imei { get; set; }
        public bool BO_Expiro { get; set; }
        public System.DateTime FE_Registro { get; set; }
        public bool BO_Activo { get; set; }
        public string TX_IDRegistroGoogle { get; set; }
    
        public virtual MW_Cargos MW_Cargos { get; set; }
        public virtual MW_LocacionEstados MW_LocacionEstados { get; set; }
        public virtual ICollection<MW_VisitadoresHistorial> MW_VisitadoresHistorial { get; set; }
        public virtual ICollection<MW_AprobacionesUsuarios> MW_AprobacionesUsuarios { get; set; }
        public virtual ICollection<MW_DescuentosUsuarios> MW_DescuentosUsuarios { get; set; }
        public virtual ICollection<MW_FichasAcceso> MW_FichasAcceso { get; set; }
        public virtual ICollection<MW_UsuariosResponsabilidades> MW_UsuariosResponsabilidades { get; set; }
        public virtual ICollection<MWS_UsuarioAprobacion> MWS_UsuarioAprobacion { get; set; }
        public virtual ICollection<MWS_UsuarioDispensado> MWS_UsuarioDispensado { get; set; }
        public virtual ICollection<MWS_CierreDistribucion> MWS_CierreDistribucion { get; set; }
        public virtual ICollection<MWS_AprDistribucion> MWS_AprDistribucion { get; set; }
        public virtual ICollection<MW_UsuariosRoles> MW_UsuariosRoles { get; set; }
    }
}
