//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_VisitadoresHistorial
    {
        public MW_VisitadoresHistorial()
        {
            this.MW_Aprobaciones = new HashSet<MW_Aprobaciones>();
            this.MWS_FicheroEspejo = new HashSet<MWS_FicheroEspejo>();
            this.MWS_NotaEntregaCabecera = new HashSet<MWS_NotaEntregaCabecera>();
            this.MWS_ValidaVisitadores = new HashSet<MWS_ValidaVisitadores>();
        }
    
        public long ID_VisitadoresHistorial { get; set; }
        public int ID_Visitador { get; set; }
        public short ID_Region { get; set; }
        public short ID_Linea { get; set; }
        public short ID_Zona { get; set; }
        public short ID_CicloIni { get; set; }
        public Nullable<short> ID_CicloFin { get; set; }
        public System.DateTime FE_Registro { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual ICollection<MW_Aprobaciones> MW_Aprobaciones { get; set; }
        public virtual MW_Ciclos MW_Ciclos { get; set; }
        public virtual MW_Ciclos MW_Ciclos1 { get; set; }
        public virtual MW_Lineas MW_Lineas { get; set; }
        public virtual MW_Regiones MW_Regiones { get; set; }
        public virtual MW_Usuarios MW_Usuarios { get; set; }
        public virtual MW_Zonas MW_Zonas { get; set; }
        public virtual ICollection<MWS_FicheroEspejo> MWS_FicheroEspejo { get; set; }
        public virtual ICollection<MWS_NotaEntregaCabecera> MWS_NotaEntregaCabecera { get; set; }
        public virtual ICollection<MWS_ValidaVisitadores> MWS_ValidaVisitadores { get; set; }
    }
}
