//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_Zonas
    {
        public MW_Zonas()
        {
            this.MW_VisitadoresHistorial = new HashSet<MW_VisitadoresHistorial>();
        }
    
        public short ID_Zona { get; set; }
        public short ID_Region { get; set; }
        public short ID_Linea { get; set; }
        public string TX_Zona { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual MW_Lineas MW_Lineas { get; set; }
        public virtual MW_Regiones MW_Regiones { get; set; }
        public virtual ICollection<MW_VisitadoresHistorial> MW_VisitadoresHistorial { get; set; }
    }
}
