//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWS_Configuraciones
    {
        public short ID_Configuracion { get; set; }
        public decimal NU_UnidadRedondeo { get; set; }
        public bool BO_PorUnidadManejo { get; set; }
        public bool BO_ForzarUnidad { get; set; }
        public short NU_DiasVigencia { get; set; }
    }
}
