//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWS_MarcasSIDEX
    {
        public MWS_MarcasSIDEX()
        {
            this.MWS_Articulos = new HashSet<MWS_Articulos>();
        }
    
        public short ID_MarcaSIDEX { get; set; }
        public Nullable<short> ID_MarcaMedinet { get; set; }
        public string TX_IDMarcaCliente { get; set; }
        public string TX_Marca { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual MW_Marcas MW_Marcas { get; set; }
        public virtual ICollection<MWS_Articulos> MWS_Articulos { get; set; }
    }
}
