//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWS_Articulos
    {
        public MWS_Articulos()
        {
            this.MWS_ConfigDistribucion = new HashSet<MWS_ConfigDistribucion>();
            this.MWS_Existencias = new HashSet<MWS_Existencias>();
            this.MWS_NoContFichero = new HashSet<MWS_NoContFichero>();
            this.MWS_NotaEntregaDetalle = new HashSet<MWS_NotaEntregaDetalle>();
        }
    
        public int ID_Articulo { get; set; }
        public string TX_IDArticuloCliente { get; set; }
        public string TX_Articulo { get; set; }
        public string TX_ArticuloAbr { get; set; }
        public short ID_Marca { get; set; }
        public short ID_TipoArticulo { get; set; }
        public short ID_UnidadManejoPri { get; set; }
        public int NU_UnidadManejo { get; set; }
        public short ID_UnidadManejoSec { get; set; }
        public decimal NU_Peso_KG { get; set; }
        public decimal NU_Pie_CUB { get; set; }
        public bool BO_Lote { get; set; }
        public bool BO_Activo { get; set; }
        public short ID_MarcaSIDEX { get; set; }
    
        public virtual MW_Marcas MW_Marcas { get; set; }
        public virtual MWS_TipoArticulos MWS_TipoArticulos { get; set; }
        public virtual MWS_UnidadManejo MWS_UnidadManejo { get; set; }
        public virtual MWS_UnidadManejo MWS_UnidadManejo1 { get; set; }
        public virtual ICollection<MWS_ConfigDistribucion> MWS_ConfigDistribucion { get; set; }
        public virtual ICollection<MWS_Existencias> MWS_Existencias { get; set; }
        public virtual ICollection<MWS_NoContFichero> MWS_NoContFichero { get; set; }
        public virtual ICollection<MWS_NotaEntregaDetalle> MWS_NotaEntregaDetalle { get; set; }
        public virtual MWS_MarcasSIDEX MWS_MarcasSIDEX { get; set; }
    }
}
