//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWS_NotaEntregaDetalle
    {
        public long ID_NotaEntrega { get; set; }
        public int ID_Articulo { get; set; }
        public string TX_Lote { get; set; }
        public short NU_UnidadEntregar { get; set; }
        public decimal NU_UMEntregar { get; set; }
        public decimal NU_Costo { get; set; }
        public string TX_Ubicacion { get; set; }
    
        public virtual MWS_NotaEntregaCabecera MWS_NotaEntregaCabecera { get; set; }
        public virtual MWS_Articulos MWS_Articulos { get; set; }
    }
}
