//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWS_UnidadManejo
    {
        public MWS_UnidadManejo()
        {
            this.MWS_Articulos = new HashSet<MWS_Articulos>();
            this.MWS_Articulos1 = new HashSet<MWS_Articulos>();
        }
    
        public short ID_UnidadManejo { get; set; }
        public string TX_UnidadManejo { get; set; }
        public bool BO_Activo { get; set; }
        public string TX_IDUnidadManejoCliente { get; set; }
    
        public virtual ICollection<MWS_Articulos> MWS_Articulos { get; set; }
        public virtual ICollection<MWS_Articulos> MWS_Articulos1 { get; set; }
    }
}
