//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWS_ExistenciasRechazadas
    {
        public string TX_IDArticuloCliente { get; set; }
        public string TX_Lote { get; set; }
        public string TX_Ubicacion { get; set; }
        public Nullable<System.DateTime> FE_VencimientoLote { get; set; }
        public int NU_CantidadPrimaria { get; set; }
        public int NU_CantidadSecundaria { get; set; }
        public decimal NU_UltimoCosto { get; set; }
    }
}
