//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWS_NotaEntregaCabecera
    {
        public MWS_NotaEntregaCabecera()
        {
            this.MWS_NotaEntregaDetalle = new HashSet<MWS_NotaEntregaDetalle>();
        }
    
        public long ID_NotaEntrega { get; set; }
        public short ID_Ciclo { get; set; }
        public long ID_VisitadoresHistorial { get; set; }
        public System.DateTime FE_Registro { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual MW_Ciclos MW_Ciclos { get; set; }
        public virtual ICollection<MWS_NotaEntregaDetalle> MWS_NotaEntregaDetalle { get; set; }
        public virtual MW_VisitadoresHistorial MW_VisitadoresHistorial { get; set; }
    }
}
