//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWS_ArticulosRechazados
    {
        public string TX_IDArticuloCliente { get; set; }
        public string TX_Articulo { get; set; }
        public string TX_ArticuloAbr { get; set; }
        public string TX_IDMarcaCliente { get; set; }
        public string TX_IDTipoArticuloCliente { get; set; }
        public string TX_IDUnidadManejoClientePri { get; set; }
        public int NU_UnidadManejo { get; set; }
        public string TX_IDUnidadManejoClienteSec { get; set; }
        public decimal NU_Peso_KG { get; set; }
        public decimal NU_Pie_CUB { get; set; }
        public bool BO_Lote { get; set; }
        public bool BO_Activo { get; set; }
    }
}
