//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWS_FicheroEspejo
    {
        public short ID_CicloDistribucion { get; set; }
        public short ID_CicloFichero { get; set; }
        public long ID_VisitadoresHistorial { get; set; }
        public short ID_Linea { get; set; }
        public short ID_Especialidad { get; set; }
        public short ID_Clasificacion { get; set; }
        public int NU_Fichados { get; set; }
        public int NU_Revisita { get; set; }
    
        public virtual MW_Ciclos MW_Ciclos { get; set; }
        public virtual MW_Ciclos MW_Ciclos1 { get; set; }
        public virtual MW_ClasificacionMedicos MW_ClasificacionMedicos { get; set; }
        public virtual MW_Especialidades MW_Especialidades { get; set; }
        public virtual MW_VisitadoresHistorial MW_VisitadoresHistorial { get; set; }
    }
}
