//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWS_ValidaVisitadores
    {
        public long ID_ValidaVisitadores { get; set; }
        public short ID_CicloDistribucion { get; set; }
        public long ID_VisitadoresHistorial { get; set; }
        public short ID_Visitador { get; set; }
        public short ID_Region { get; set; }
        public short ID_Linea { get; set; }
        public bool BO_Activo { get; set; }
    
        public virtual MW_Ciclos MW_Ciclos { get; set; }
        public virtual MW_VisitadoresHistorial MW_VisitadoresHistorial { get; set; }
    }
}
