//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWS_ConfigDistribucion
    {
        public long ID_ConfigDistribucion { get; set; }
        public short ID_Ciclo { get; set; }
        public int ID_Articulo { get; set; }
        public short ID_Linea { get; set; }
        public short ID_Especialidad { get; set; }
        public short ID_Clasificacion { get; set; }
        public short NU_CantidadEntregar { get; set; }
    
        public virtual MW_Ciclos MW_Ciclos { get; set; }
        public virtual MW_ClasificacionMedicos MW_ClasificacionMedicos { get; set; }
        public virtual MW_Especialidades MW_Especialidades { get; set; }
        public virtual MW_Lineas MW_Lineas { get; set; }
        public virtual MWS_Articulos MWS_Articulos { get; set; }
    }
}
