//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWS_CargaInv
    {
        public short ID_CargaInv { get; set; }
        public short ID_Ciclo { get; set; }
        public string TX_RutaArchivo { get; set; }
        public System.DateTime FE_Registro { get; set; }
    
        public virtual MW_Ciclos MW_Ciclos { get; set; }
    }
}
