//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedinetWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MedinetWebLimitedEntities : DbContext
    {
        public MedinetWebLimitedEntities()
            : base("name=MedinetWebLimitedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_MWL_GetFicheroByZonaAndText_Result> SP_MWL_GetFicheroByZonaAndText(Nullable<int> zona)
        {
            var zonaParameter = zona.HasValue ?
                new ObjectParameter("zona", zona) :
                new ObjectParameter("zona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetFicheroByZonaAndText_Result>("SP_MWL_GetFicheroByZonaAndText", zonaParameter);
        }
    
        public virtual ObjectResult<SP_MWL_InsertVisitaMedico_Result> SP_MWL_InsertVisitaMedico(Nullable<int> visitadorID, string registro, string fecha, string tipo, string acompanante)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var registroParameter = registro != null ?
                new ObjectParameter("registro", registro) :
                new ObjectParameter("registro", typeof(string));
    
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var acompananteParameter = acompanante != null ?
                new ObjectParameter("acompanante", acompanante) :
                new ObjectParameter("acompanante", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_InsertVisitaMedico_Result>("SP_MWL_InsertVisitaMedico", visitadorIDParameter, registroParameter, fechaParameter, tipoParameter, acompananteParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetInfoFichero_Result> SP_MWL_GetInfoFichero(Nullable<int> visitadorID, string registro)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var registroParameter = registro != null ?
                new ObjectParameter("registro", registro) :
                new ObjectParameter("registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetInfoFichero_Result>("SP_MWL_GetInfoFichero", visitadorIDParameter, registroParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetVisitasMedicos_Result> SP_MWL_GetVisitasMedicos(Nullable<int> visitadorID)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetVisitasMedicos_Result>("SP_MWL_GetVisitasMedicos", visitadorIDParameter);
        }
    
        public virtual ObjectResult<SP_MWL_EliminarVisitaMedico_Result> SP_MWL_EliminarVisitaMedico(Nullable<int> visitadorID, string registro, string tipo)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var registroParameter = registro != null ?
                new ObjectParameter("registro", registro) :
                new ObjectParameter("registro", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_EliminarVisitaMedico_Result>("SP_MWL_EliminarVisitaMedico", visitadorIDParameter, registroParameter, tipoParameter);
        }
    
        public virtual ObjectResult<SP_GetTipoVisitaAllowed_Result> SP_MWL_GetTipoVisitaAllowed(Nullable<int> visitadorID, string registro)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var registroParameter = registro != null ?
                new ObjectParameter("registro", registro) :
                new ObjectParameter("registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetTipoVisitaAllowed_Result>("SP_MWL_GetTipoVisitaAllowed", visitadorIDParameter, registroParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetFarmaciasByZonaAndText_Result> SP_MWL_GetFarmaciasByZonaAndText(Nullable<int> zona)
        {
            var zonaParameter = zona.HasValue ?
                new ObjectParameter("zona", zona) :
                new ObjectParameter("zona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetFarmaciasByZonaAndText_Result>("SP_MWL_GetFarmaciasByZonaAndText", zonaParameter);
        }
    
        public virtual ObjectResult<SP_MWL_InsertVisitaFarmacia_Result> SP_MWL_InsertVisitaFarmacia(Nullable<int> visitadorID, string numero, string fecha, string tipo, string farmacia)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var farmaciaParameter = farmacia != null ?
                new ObjectParameter("farmacia", farmacia) :
                new ObjectParameter("farmacia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_InsertVisitaFarmacia_Result>("SP_MWL_InsertVisitaFarmacia", visitadorIDParameter, numeroParameter, fechaParameter, tipoParameter, farmaciaParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetInfoFarmacia_Result> SP_MWL_GetInfoFarmacia(Nullable<int> visitadorID, string registro)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var registroParameter = registro != null ?
                new ObjectParameter("registro", registro) :
                new ObjectParameter("registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetInfoFarmacia_Result>("SP_MWL_GetInfoFarmacia", visitadorIDParameter, registroParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetVisitasFarmacias_Result> SP_MWL_GetVisitasFarmacias(Nullable<int> visitadorID)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetVisitasFarmacias_Result>("SP_MWL_GetVisitasFarmacias", visitadorIDParameter);
        }
    
        public virtual ObjectResult<SP_MWL_EliminarVisitaFarmacia_Result> SP_MWL_EliminarVisitaFarmacia(Nullable<int> visitadorID, string numero, string tipo, string fecha)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_EliminarVisitaFarmacia_Result>("SP_MWL_EliminarVisitaFarmacia", visitadorIDParameter, numeroParameter, tipoParameter, fechaParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetHospitalByZonaAndText_Result> SP_MWL_GetHospitalByZonaAndText(Nullable<int> zona)
        {
            var zonaParameter = zona.HasValue ?
                new ObjectParameter("zona", zona) :
                new ObjectParameter("zona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetHospitalByZonaAndText_Result>("SP_MWL_GetHospitalByZonaAndText", zonaParameter);
        }
    
        public virtual ObjectResult<SP_MWL_InsertVisitaHospital_Result> SP_MWL_InsertVisitaHospital(Nullable<int> visitadorID, string numero, string fecha, string tipo, string hospital, Nullable<int> medicos, string servicio)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var hospitalParameter = hospital != null ?
                new ObjectParameter("hospital", hospital) :
                new ObjectParameter("hospital", typeof(string));
    
            var medicosParameter = medicos.HasValue ?
                new ObjectParameter("medicos", medicos) :
                new ObjectParameter("medicos", typeof(int));
    
            var servicioParameter = servicio != null ?
                new ObjectParameter("servicio", servicio) :
                new ObjectParameter("servicio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_InsertVisitaHospital_Result>("SP_MWL_InsertVisitaHospital", visitadorIDParameter, numeroParameter, fechaParameter, tipoParameter, hospitalParameter, medicosParameter, servicioParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetInfoHospital_Result> SP_MWL_GetInfoHospital(Nullable<int> visitadorID, string registro)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var registroParameter = registro != null ?
                new ObjectParameter("registro", registro) :
                new ObjectParameter("registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetInfoHospital_Result>("SP_MWL_GetInfoHospital", visitadorIDParameter, registroParameter);
        }
    
        public virtual ObjectResult<SP_MWL_EliminarVisitaHospital_Result> SP_MWL_EliminarVisitaHospital(Nullable<int> visitadorID, string numero, string tipo, string fecha, string servicio)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            var servicioParameter = servicio != null ?
                new ObjectParameter("servicio", servicio) :
                new ObjectParameter("servicio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_EliminarVisitaHospital_Result>("SP_MWL_EliminarVisitaHospital", visitadorIDParameter, numeroParameter, tipoParameter, fechaParameter, servicioParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetVisitasHospitales_Result> SP_MWL_GetVisitasHospitales(Nullable<int> visitadorID)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetVisitasHospitales_Result>("SP_MWL_GetVisitasHospitales", visitadorIDParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetCoberturas_Result> SP_MWL_GetCoberturas(Nullable<int> visitadorID)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetCoberturas_Result>("SP_MWL_GetCoberturas", visitadorIDParameter);
        }
    
        public virtual ObjectResult<string> SP_MWL_GetClinicas(Nullable<int> visitadorID)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_MWL_GetClinicas", visitadorIDParameter);
        }
    
        public virtual ObjectResult<string> SP_MWL_GetRutas(Nullable<int> visitadorID)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_MWL_GetRutas", visitadorIDParameter);
        }
    
        public virtual int SP_MWL_AltaMedico(Nullable<int> visitadorID, string nroSanitario, string doctor, string ruta, string clinica, string especialidad, string clasificacion, string direccion, string revisita)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var nroSanitarioParameter = nroSanitario != null ?
                new ObjectParameter("nroSanitario", nroSanitario) :
                new ObjectParameter("nroSanitario", typeof(string));
    
            var doctorParameter = doctor != null ?
                new ObjectParameter("doctor", doctor) :
                new ObjectParameter("doctor", typeof(string));
    
            var rutaParameter = ruta != null ?
                new ObjectParameter("ruta", ruta) :
                new ObjectParameter("ruta", typeof(string));
    
            var clinicaParameter = clinica != null ?
                new ObjectParameter("clinica", clinica) :
                new ObjectParameter("clinica", typeof(string));
    
            var especialidadParameter = especialidad != null ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(string));
    
            var clasificacionParameter = clasificacion != null ?
                new ObjectParameter("clasificacion", clasificacion) :
                new ObjectParameter("clasificacion", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var revisitaParameter = revisita != null ?
                new ObjectParameter("revisita", revisita) :
                new ObjectParameter("revisita", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWL_AltaMedico", visitadorIDParameter, nroSanitarioParameter, doctorParameter, rutaParameter, clinicaParameter, especialidadParameter, clasificacionParameter, direccionParameter, revisitaParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetFichero_Result> SP_MWL_GetFichero(Nullable<int> zona)
        {
            var zonaParameter = zona.HasValue ?
                new ObjectParameter("zona", zona) :
                new ObjectParameter("zona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetFichero_Result>("SP_MWL_GetFichero", zonaParameter);
        }
    
        public virtual int SP_MWL_BajaMedico(Nullable<int> visitadorID, string registro)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var registroParameter = registro != null ?
                new ObjectParameter("registro", registro) :
                new ObjectParameter("registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWL_BajaMedico", visitadorIDParameter, registroParameter);
        }
    
        public virtual int SP_MW_MoverFicheroAsistido(Nullable<int> idCicloOrigen, Nullable<int> idCicloDestino, Nullable<int> iDOrigen, Nullable<int> iDDestino)
        {
            var idCicloOrigenParameter = idCicloOrigen.HasValue ?
                new ObjectParameter("idCicloOrigen", idCicloOrigen) :
                new ObjectParameter("idCicloOrigen", typeof(int));
    
            var idCicloDestinoParameter = idCicloDestino.HasValue ?
                new ObjectParameter("idCicloDestino", idCicloDestino) :
                new ObjectParameter("idCicloDestino", typeof(int));
    
            var iDOrigenParameter = iDOrigen.HasValue ?
                new ObjectParameter("IDOrigen", iDOrigen) :
                new ObjectParameter("IDOrigen", typeof(int));
    
            var iDDestinoParameter = iDDestino.HasValue ?
                new ObjectParameter("IDDestino", iDDestino) :
                new ObjectParameter("IDDestino", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MW_MoverFicheroAsistido", idCicloOrigenParameter, idCicloDestinoParameter, iDOrigenParameter, iDDestinoParameter);
        }
    
        public virtual ObjectResult<SP_MW_Visitadores_FicVis2_Result> SP_MW_Visitadores_FicVis2(Nullable<int> ciclo, Nullable<int> linea, Nullable<int> region)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var lineaParameter = linea.HasValue ?
                new ObjectParameter("linea", linea) :
                new ObjectParameter("linea", typeof(int));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MW_Visitadores_FicVis2_Result>("SP_MW_Visitadores_FicVis2", cicloParameter, lineaParameter, regionParameter);
        }
    
        public virtual ObjectResult<SP_MWL_Ciclos_Act_Result> SP_MWL_Ciclos_Act()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_Ciclos_Act_Result>("SP_MWL_Ciclos_Act");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_MWL_AltaMedicoValidar(Nullable<int> visitadorID, string nroSanitario)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var nroSanitarioParameter = nroSanitario != null ?
                new ObjectParameter("nroSanitario", nroSanitario) :
                new ObjectParameter("nroSanitario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_MWL_AltaMedicoValidar", visitadorIDParameter, nroSanitarioParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetFarmacias_Result> SP_MWL_GetFarmacias(Nullable<int> visitadorID)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetFarmacias_Result>("SP_MWL_GetFarmacias", visitadorIDParameter);
        }
    
        public virtual int SP_MWL_AltaFarmacia(Nullable<int> visitadorID, Nullable<int> idFarmacia)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var idFarmaciaParameter = idFarmacia.HasValue ?
                new ObjectParameter("idFarmacia", idFarmacia) :
                new ObjectParameter("idFarmacia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWL_AltaFarmacia", visitadorIDParameter, idFarmaciaParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetFicheroFarmacias_Result> SP_MWL_GetFicheroFarmacias(Nullable<int> visitadorID)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetFicheroFarmacias_Result>("SP_MWL_GetFicheroFarmacias", visitadorIDParameter);
        }
    
        public virtual int SP_MWL_BajaFarmacia(Nullable<int> visitadorID, string numero)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWL_BajaFarmacia", visitadorIDParameter, numeroParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetHospitales_Result> SP_MWL_GetHospitales(Nullable<int> visitadorID)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetHospitales_Result>("SP_MWL_GetHospitales", visitadorIDParameter);
        }
    
        public virtual int SP_MWL_AltaHospital(Nullable<int> visitadorID, Nullable<int> idHospital)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var idHospitalParameter = idHospital.HasValue ?
                new ObjectParameter("idHospital", idHospital) :
                new ObjectParameter("idHospital", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWL_AltaHospital", visitadorIDParameter, idHospitalParameter);
        }
    
        public virtual int SP_MWL_BajaHospital(Nullable<int> visitadorID, string numero)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MWL_BajaHospital", visitadorIDParameter, numeroParameter);
        }
    
        public virtual ObjectResult<SP_MWL_GetFicheroHospitales_Result> SP_MWL_GetFicheroHospitales(Nullable<int> visitadorID)
        {
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MWL_GetFicheroHospitales_Result>("SP_MWL_GetFicheroHospitales", visitadorIDParameter);
        }
    
        public virtual int SP_MW_EliminarFicheroAsistido(Nullable<int> idCiclo, Nullable<int> visitadorID)
        {
            var idCicloParameter = idCiclo.HasValue ?
                new ObjectParameter("idCiclo", idCiclo) :
                new ObjectParameter("idCiclo", typeof(int));
    
            var visitadorIDParameter = visitadorID.HasValue ?
                new ObjectParameter("visitadorID", visitadorID) :
                new ObjectParameter("visitadorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MW_EliminarFicheroAsistido", idCicloParameter, visitadorIDParameter);
        }
    }
}
